using System.Buffers;
using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Shared.Shuttles.Components;
using Content.Shared._Rat.Shuttles.Components;
using Content.Shared.Shuttles.UI.MapObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Client._Rat.SpaceEvents; // Rat

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleMapControl : BaseShuttleControl
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IInputManager _inputs = default!;
    [Dependency] private readonly IMapManager _mapManager = default!;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;

    private EmpZoneClientSystem _empZone = default!;

    protected override bool Draggable => true;

    public bool ShowBeacons = true;
    public MapId ViewingMap = MapId.Nullspace;

    private EntityUid? _shuttleEntity;

    private readonly Font _font;

    private readonly EntityQuery<PhysicsComponent> _physicsQuery;

    /// <summary>
    /// Toggles FTL mode on. This shows a pre-vis for FTLing a grid.
    /// </summary>
    public bool FtlMode;

    private Angle _ftlAngle;

    /// <summary>
    /// Are we currently in FTL.
    /// </summary>
    public bool InFtl;

    /// <summary>
    /// Raised when a request to FTL to a particular spot is raised.
    /// </summary>
    public event Action<MapCoordinates, Angle>? RequestFTL;

    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    /// <summary>
    /// Set every draw to determine the beacons that are clickable for mouse events
    /// </summary>
    private List<IMapObject> _beacons = new();

    // Per frame data to avoid re-allocating
    private readonly List<IMapObject> _mapObjects = new();
    private readonly Dictionary<Color, List<Vector2>> _verts = new();
    private readonly Dictionary<Color, List<Vector2>> _edges = new();
    private readonly Dictionary<Color, List<(Vector2, string)>> _strings = new();
    private readonly List<ShuttleExclusionObject> _viewportExclusions = new();

    //Changing from 256 512 512 to 256 2048 2048, this shows in testing to be about 4000 units ish. presume 1024>2048 units
    public ShuttleMapControl() : base(640f, 5120f, 5120f)
    {
        RobustXamlLoader.Load(this);
        _shuttles = EntManager.System<ShuttleSystem>();
        _xformSystem = EntManager.System<SharedTransformSystem>();
		_empZone = EntManager.System<EmpZoneClientSystem>();
        var cache = IoCManager.Resolve<IResourceCache>();

        _physicsQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        _font = new VectorFont(cache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSans-Regular.ttf"), 10);
    }

    public void SetMap(MapId mapId, Vector2 offset, bool recentering = false)
    {
        ViewingMap = mapId;
        TargetOffset = offset;
        Recentering = recentering;
    }

    public void SetShuttle(EntityUid? entity)
    {
        _shuttleEntity = entity;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        // No move for you.
        if (FtlMode)
            return;

        base.MouseMove(args);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (FtlMode && ViewingMap != MapId.Nullspace)
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                var mapUid = _mapManager.GetMapEntityId(ViewingMap);

                var beaconsOnly = EntManager.TryGetComponent(mapUid, out FTLDestinationComponent? destComp) &&
                                  destComp.BeaconsOnly;

                var mapTransform = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);

                if (beaconsOnly && TryGetBeacon(_beacons, mapTransform, args.RelativePixelPosition, PixelRect, out var foundBeacon, out _))
                {
                    RequestBeaconFTL?.Invoke(foundBeacon.Entity, _ftlAngle);
                }
                else
                {
                    // We'll send the "adjusted" position and server will adjust it back when relevant.
                    var mapCoords = new MapCoordinates(InverseMapPosition(args.RelativePixelPosition), ViewingMap);
                    RequestFTL?.Invoke(mapCoords, _ftlAngle);
                }
            }
        }

        base.KeyBindUp(args);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        // Scroll handles FTL rotation if you're in FTL mode.
        if (FtlMode)
        {
            _ftlAngle += Angle.FromDegrees(15f) * args.Delta.Y;
            _ftlAngle = _ftlAngle.Reduced();
            return;
        }

        base.MouseWheel(args);
    }

    // Rat-start
    private void DrawCoordinateGrid(DrawingHandleScreen handle)
    {
        DrawBacking(handle);

        const float step = 500f;
        var gridColor = new Color(0.2f, 0.2f, 0.2f, 0.8f);
        var axisColor = new Color(0.4f, 0.4f, 0.4f, 1f);

        var startX = MathF.Floor((Offset.X - WorldRange) / step) * step;
        var endX = MathF.Ceiling((Offset.X + WorldRange) / step) * step;
        var startY = MathF.Floor((Offset.Y - WorldRange) / step) * step;
        var endY = MathF.Ceiling((Offset.Y + WorldRange) / step) * step;

        var screenH = PixelHeight;
        var screenW = PixelWidth;

        for (var wx = startX; wx <= endX; wx += step)
        {
            var sx = ScalePosition(new Vector2(wx - Offset.X, 0f)).X;
            var color = MathF.Abs(wx) < 0.1f ? axisColor : gridColor;
            handle.DrawLine(new Vector2(sx, 0), new Vector2(sx, screenH), color);
        }

        for (var wy = startY; wy <= endY; wy += step)
        {
            var sy = ScalePosition(new Vector2(0f, -(wy - Offset.Y))).Y;
            var color = MathF.Abs(wy) < 0.1f ? axisColor : gridColor;
            handle.DrawLine(new Vector2(0, sy), new Vector2(screenW, sy), color);
        }
    }
    // Rat-end

    // Rat-start
    private static void DrawFilledRing(DrawingHandleScreen handle, Vector2 center,
        float innerRadius, float outerRadius, Color fillColor, Color outlineColor, int segments = 64)
    {
        var verts = new Vector2[segments * 6];
        for (int i = 0; i < segments; i++)
        {
            float a0 = MathF.Tau * i / segments;
            float a1 = MathF.Tau * (i + 1) / segments;
            var d0 = new Vector2(MathF.Cos(a0), MathF.Sin(a0));
            var d1 = new Vector2(MathF.Cos(a1), MathF.Sin(a1));
            verts[i * 6 + 0] = center + d0 * innerRadius;
            verts[i * 6 + 1] = center + d0 * outerRadius;
            verts[i * 6 + 2] = center + d1 * outerRadius;
            verts[i * 6 + 3] = center + d0 * innerRadius;
            verts[i * 6 + 4] = center + d1 * outerRadius;
            verts[i * 6 + 5] = center + d1 * innerRadius;
        }
        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, verts, fillColor);

        var outerVerts = new Vector2[segments];
        var innerVerts = new Vector2[segments];
        for (int i = 0; i < segments; i++)
        {
            float a = MathF.Tau * i / segments;
            var dir = new Vector2(MathF.Cos(a), MathF.Sin(a));
            outerVerts[i] = center + dir * outerRadius;
            innerVerts[i] = center + dir * innerRadius;
        }
        handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, outerVerts, outlineColor);
        handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, innerVerts, outlineColor);
    }

    private void DrawRatZones(DrawingHandleScreen handle)
    {
        var matty = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);
        var worldOrigin = Vector2.Transform(Vector2.Zero, matty);
        worldOrigin = worldOrigin with { Y = -worldOrigin.Y };
        var screenOrigin = ScalePosition(worldOrigin);

        // Center
        handle.DrawCircle(screenOrigin, 500f * MinimapScale, new Color(1f, 0f, 0f, 0.03f));
        handle.DrawCircle(screenOrigin, 500f * MinimapScale, new Color(1f, 0f, 0f, 0.2f), filled: false);

        // Outer ring
        DrawFilledRing(handle, screenOrigin,
            4000f * MinimapScale, 4500f * MinimapScale,
            new Color(0f, 1f, 0f, 0.03f), new Color(0f, 1f, 0f, 0.2f));

        // Hadal zone
        DrawFilledRing(handle, screenOrigin,
            10000f * MinimapScale, 20000f * MinimapScale,
            new Color(1f, 0f, 0f, 0.01f), new Color(1f, 0f, 0f, 0.1f));

	    foreach (var (_, (center, radius)) in _empZone.ActiveZones)
        {
            var empRelPos = Vector2.Transform(center, matty);
            empRelPos = empRelPos with { Y = -empRelPos.Y };
            var empScreenPos = ScalePosition(empRelPos);
            var empScreenRadius = radius * MinimapScale;

            handle.DrawCircle(empScreenPos, empScreenRadius, new Color(0f, 0.8f, 1f, 0.03f));
            handle.DrawCircle(empScreenPos, empScreenRadius, new Color(0f, 0.8f, 1f, 0.2f), filled: false);
        }
    }
    // Rat-end

    /// <summary>
    /// Gets the map objects that intersect the viewport.
    /// </summary>
    /// <param name="mapObjects"></param>
    /// <returns></returns>
    private List<IMapObject> GetViewportMapObjects(Matrix3x2 matty, List<IMapObject> mapObjects)
    {
        var results = new List<IMapObject>();
        var enlargement = new Vector2i((int) (16 * UIScale), (int) (16 * UIScale));
        var viewBox = new UIBox2i(Vector2i.Zero - enlargement, PixelSize + enlargement);

        foreach (var mapObj in mapObjects)
        {
            // If it's a grid-map skip it.
            if (mapObj is GridMapObject gridObj && EntManager.HasComponent<MapComponent>(gridObj.Entity))
                continue;

            var mapCoords = _shuttles.GetMapCoordinates(mapObj);
			// Rat-start
			if (mapCoords == MapCoordinates.Nullspace)
                continue;
			// Rat-end

            var relativePos = Vector2.Transform(mapCoords.Position, matty);
            relativePos = relativePos with { Y = -relativePos.Y };
            var uiPosition = ScalePosition(relativePos);

            if (!viewBox.Contains(uiPosition.Floored()))
                continue;

            results.Add(mapObj);
        }

        return results;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (ViewingMap == MapId.Nullspace)
            return;

        var mapObjects = _mapObjects;
        DrawRecenter();

        if (InFtl || mapObjects.Count == 0)
        {
            DrawBacking(handle);
            DrawNoSignal(handle);
            return;
        }

        DrawCoordinateGrid(handle); // Rat

        DrawRatZones(handle);

        var viewedMapUid = _mapManager.GetMapEntityId(ViewingMap);
        var matty = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);
        var realTime = _timing.RealTime;
        var viewBox = new Box2(Offset - WorldRangeVector, Offset + WorldRangeVector);
        var viewportObjects = GetViewportMapObjects(matty, mapObjects);
        _viewportExclusions.Clear();

        // Draw our FTL range + no FTL zones
        // Do it up here because we want this layered below most things.
        if (FtlMode)
        {
            if (EntManager.TryGetComponent<TransformComponent>(_shuttleEntity, out var shuttleXform))
            {
                var gridUid = _shuttleEntity.Value;
                var gridPhysics = _physicsQuery.GetComponent(gridUid);
                var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                gridPos = Maps.GetGridPosition((gridUid, gridPhysics), gridPos, gridRot);

                var gridRelativePos = Vector2.Transform(gridPos, matty);
                gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                var gridUiPos = ScalePosition(gridRelativePos);

                var range = _shuttles.GetFTLRange(gridUid);
                range *= MinimapScale;
                handle.DrawCircle(gridUiPos, range, Color.Gold, filled: false);
            }
        }

        var exclusionColor = Color.Red;

        // Exclusions need a bumped range so we check all the ones on the map.
        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleExclusionObject exclusion)
                continue;

            // Check if it even intersects the viewport.
            var coords = EntManager.GetCoordinates(exclusion.Coordinates);
            var mapCoords = _xformSystem.ToMapCoordinates(coords);
            var enlargedBounds = viewBox.Enlarged(exclusion.Range);

            if (mapCoords.MapId != ViewingMap ||
                !enlargedBounds.Contains(mapCoords.Position))
            {
                continue;
            }

            var adjustedPos = Vector2.Transform(mapCoords.Position, matty);
            var localPos = ScalePosition(adjustedPos with { Y = -adjustedPos.Y});
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor.WithAlpha(0.05f));
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor, filled: false);

            _viewportExclusions.Add(exclusion);
        }

        _verts.Clear();
        _edges.Clear();
        _strings.Clear();

        // Add beacons if relevant.
        var beaconsOnly = _shuttles.IsBeaconMap(viewedMapUid);
        var controlLocalBounds = PixelRect;
        _beacons.Clear();

        if (ShowBeacons)
        {
            var beaconColor = Color.AliceBlue;

            foreach (var (beaconName, coords, mapO) in GetBeacons(viewportObjects, matty, controlLocalBounds))
            {
                var localPos = Vector2.Transform(coords.Position, matty);
                localPos = localPos with { Y = -localPos.Y };
                var beaconUiPos = ScalePosition(localPos);
                var mapObject = GetMapObject(localPos, Angle.Zero, scale: 0.75f, scalePosition: true);

                var existingVerts = _verts.GetOrNew(beaconColor);
                var existingEdges = _edges.GetOrNew(beaconColor);

                AddMapObject(existingEdges, existingVerts, mapObject);
                _beacons.Add(mapO);

                var existingStrings = _strings.GetOrNew(beaconColor);
                existingStrings.Add((beaconUiPos, beaconName));
            }
        }

        foreach (var mapObj in viewportObjects)
        {
            if (mapObj is not GridMapObject gridObj || !EntManager.TryGetComponent(gridObj.Entity, out MapGridComponent? mapGrid))
                continue;

            Entity<MapGridComponent> grid = (gridObj.Entity, mapGrid);

            IFFComponent? iffComp = null;

            if (grid.Owner != _shuttleEntity &&
                EntManager.TryGetComponent(grid, out iffComp) &&
                (iffComp.Flags & IFFFlags.Hide) != 0x0)
            {
                continue;
            }

            var gridColor = _shuttles.GetIFFColor(grid, self: _shuttleEntity == grid.Owner, component: iffComp);
            var existingVerts = _verts.GetOrNew(gridColor);
            var existingEdges = _edges.GetOrNew(gridColor);

            var gridPhysics = _physicsQuery.GetComponent(grid.Owner);
            var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(grid.Owner);
            gridPos = Maps.GetGridPosition((grid, gridPhysics), gridPos, gridRot);

            var gridRelativePos = Vector2.Transform(gridPos, matty);
            gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
            var gridUiPos = ScalePosition(gridRelativePos);
            
            if (_shuttleEntity == grid.Owner)
            {
                if (EntManager.TryGetComponent<PhysicsComponent>(grid, out var physics))
                {
                    Vector2 movementDir = physics.LinearVelocity;
                    movementDir.Y *= -1;
                    handle.DrawLine(gridUiPos, gridUiPos + movementDir.Normalized() * movementDir.Length() * 3, Color.Red);
                }
            }

            MapIconType? iconType = null;
            if (EntManager.TryGetComponent<MapIconComponent>(grid.Owner, out var mapIcon))
                iconType = mapIcon.Type;

            var mapObject = GetMapObject(gridRelativePos, Angle.Zero, iconType: iconType, scalePosition: true);
            AddMapObject(existingEdges, existingVerts, mapObject, iconType);

            if (iffComp != null && (iffComp.Flags & IFFFlags.HideLabel) != 0x0)
                continue;

            var iffText = _shuttles.GetIFFLabel(grid, self: true, component: iffComp);

            if (string.IsNullOrEmpty(iffText))
                continue;

            var existingStrings = _strings.GetOrNew(gridColor);
            existingStrings.Add((gridUiPos, iffText));
        }

        // Batch the colors whoopie
        // really only affects forks with lots of grids.
        foreach (var (color, sendVerts) in _verts)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, sendVerts, color.WithAlpha(0.05f));
        }

        foreach (var (color, sendEdges) in _edges)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.LineList, sendEdges, color);
        }

        foreach (var (color, sendStrings) in _strings)
        {
            var adjustedColor = Color.FromSrgb(color);

            foreach (var (gridUiPos, iffText) in sendStrings)
            {
                var textWidth = handle.GetDimensions(_font, iffText, 1f);
                handle.DrawString(_font, gridUiPos + textWidth with { X = -textWidth.X / 2f, Y = textWidth.Y * 0.5f }, iffText, adjustedColor);
            }
        }

        var mousePos = _inputs.MouseScreenPosition;
        var mouseLocalPos = GetLocalPosition(mousePos);

        // Draw dotted line from our own shuttle entity to mouse.
        if (FtlMode)
        {
            if (mousePos.Window != WindowId.Invalid)
            {
                // If mouse inbounds then draw it.
                if (_shuttleEntity != null && controlLocalBounds.Contains(mouseLocalPos.Floored()) &&
                    EntManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform) &&
                    shuttleXform.MapID != MapId.Nullspace)
                {
                    // If it's a beacon only map then snap the mouse to a nearby spot.
                    ShuttleBeaconObject foundBeacon = default;

                    // Check for beacons around mouse and snap to that.
                    if (beaconsOnly && TryGetBeacon(viewportObjects, matty, mouseLocalPos, controlLocalBounds, out foundBeacon, out var foundLocalPos))
                    {
                        mouseLocalPos = foundLocalPos;
                    }

                    var grid = EntManager.GetComponent<MapGridComponent>(_shuttleEntity.Value);

                    var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                    gridPos = Maps.GetGridPosition(_shuttleEntity.Value, gridPos, gridRot);

                    // do NOT apply LocalCenter operation here because it will be adjusted in FTLFree.
                    var mouseMapPos = InverseMapPosition(mouseLocalPos);

                    var ftlFree = (!beaconsOnly || foundBeacon != default) &&
                                  _shuttles.FTLFree(_shuttleEntity.Value, new EntityCoordinates(viewedMapUid, mouseMapPos), _ftlAngle, _viewportExclusions);

                    var color = ftlFree ? Color.LimeGreen : Color.Magenta;

                    var gridRelativePos = Vector2.Transform(gridPos, matty);
                    gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                    var gridUiPos = ScalePosition(gridRelativePos);

                    // Draw FTL buffer around the mouse.
                    var ourFTLBuffer = _shuttles.GetFTLBufferRange(_shuttleEntity.Value, grid);
                    ourFTLBuffer *= MinimapScale;
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, Color.Magenta.WithAlpha(0.01f));
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, Color.Magenta, filled: false);

                    // Draw line from our shuttle to target
                    // Might need to clip the line if it's too far? But my brain wasn't working so F.
                    handle.DrawDottedLine(gridUiPos, mouseLocalPos, color, (float) realTime.TotalSeconds * 30f);

                    // Draw shuttle pre-vis
                    var mouseVerts = GetMapObject(mouseLocalPos, _ftlAngle, iconType: MapIconType.Shuttle, scale: MinimapScale);

                    handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, mouseVerts.Span, color.WithAlpha(0.05f));
                    handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, mouseVerts.Span, color);

                    // Draw a notch indicating direction.
                    var ftlLength = GetMapObjectRadius() + 16f;
                    var ftlEnd = mouseLocalPos + _ftlAngle.RotateVec(new Vector2(0f, -ftlLength));

                    handle.DrawLine(mouseLocalPos, ftlEnd, color);
                }
            }
        }

        // Draw the coordinates
        var mapOffset = MidPointVector;

        if (mousePos.Window != WindowId.Invalid &&
            controlLocalBounds.Contains(mouseLocalPos.Floored()))
        {
            mapOffset = mouseLocalPos;
        }

        mapOffset = InverseMapPosition(mapOffset);
        var coordsText = $"{mapOffset.X:0.0}, {mapOffset.Y:0.0}";
        DrawData(handle, coordsText);
    }

    private void AddMapObject(List<Vector2> edges, List<Vector2> verts, ValueList<Vector2> mapObject, MapIconType? iconType = null)
    {
        if (mapObject.Count < 3)
            return;

        if (iconType == MapIconType.Station)
        {
            var tl = mapObject[0];
            var tr = mapObject[1];
            var br = mapObject[2];
            var bl = mapObject[3];

            verts.Add(tl); verts.Add(tr); verts.Add(br);
            verts.Add(tl); verts.Add(br); verts.Add(bl);

            edges.Add(tl); edges.Add(tr);
            edges.Add(tr); edges.Add(br);
            edges.Add(br); edges.Add(bl);
            edges.Add(bl); edges.Add(tl);
        }
        else
        {
            var center = Vector2.Zero;
            for (var i = 0; i < mapObject.Count; i++)
                center += mapObject[i];
            center /= mapObject.Count;

            for (var i = 0; i < mapObject.Count; i++)
            {
                var next = (i + 1) % mapObject.Count;
                verts.Add(center);
                verts.Add(mapObject[i]);
                verts.Add(mapObject[next]);
            }

            for (var i = 0; i < mapObject.Count; i++)
            {
                var next = (i + 1) % mapObject.Count;
                edges.Add(mapObject[i]);
                edges.Add(mapObject[next]);
            }
        }
    }

    /// <summary>
    /// Returns the beacons that intersect the viewport.
    /// </summary>
    private IEnumerable<(string Beacon, MapCoordinates Coordinates, IMapObject MapObject)> GetBeacons(List<IMapObject> mapObjs, Matrix3x2 mapTransform, UIBox2i area)
    {
        foreach (var mapO in mapObjs)
        {
            if (mapO is not ShuttleBeaconObject beacon)
                continue;

            var beaconCoords = EntManager.GetCoordinates(beacon.Coordinates).ToMap(EntManager, _xformSystem);
            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with {Y = -position.Y});

            // If beacon not on screen then ignore it.
            if (!area.Contains(localPos.Floored()))
                continue;

            yield return (beacon.Name, beaconCoords, mapO);
        }
    }

    private float GetMapObjectRadius(float scale = 1f) => WorldRange / 40f * scale;

    private ValueList<Vector2> GetMapObject(Vector2 localPos, Angle angle, MapIconType? iconType = null, float scale = 1f, bool scalePosition = false)
    {
        var radius = GetMapObjectRadius() * scale;
        ValueList<Vector2> mapObj;

        switch (iconType)
        {
            case MapIconType.Station:
            {
                mapObj = new ValueList<Vector2>(4)
                {
                    localPos + angle.RotateVec(new Vector2(-radius, -radius)),
                    localPos + angle.RotateVec(new Vector2(radius, -radius)),
                    localPos + angle.RotateVec(new Vector2(radius, radius)),
                    localPos + angle.RotateVec(new Vector2(-radius, radius)),
                };
                break;
            }
            case MapIconType.Shuttle:
            {
                const int segments = 15;  
                var shuttleRadius = radius * 0.8f;
                mapObj = new ValueList<Vector2>(segments);  
                for (var i = 0; i < segments; i++)  
                {  
                    var theta = (float)(2.0 * Math.PI * i / segments);  
                    mapObj.Add(localPos + new Vector2(MathF.Cos(theta), MathF.Sin(theta)) * shuttleRadius);  
                }  
                break;  
            }
            default:
            {
                const int segments = 15;
                var smallRadius = radius * 0.5f;
                mapObj = new ValueList<Vector2>(segments);
                for (var i = 0; i < segments; i++)
                {
                    var theta = (float)(2.0 * Math.PI * i / segments);
                    mapObj.Add(localPos + new Vector2(MathF.Cos(theta), MathF.Sin(theta)) * smallRadius);
                }
                break;
            }
        }

        if (scalePosition)
        {
            for (var i = 0; i < mapObj.Count; i++)
                mapObj[i] = ScalePosition(mapObj[i]);
        }

        return mapObj;
    }

    private bool TryGetBeacon(IEnumerable<IMapObject> mapObjects, Matrix3x2 mapTransform, Vector2 mousePos, UIBox2i area, out ShuttleBeaconObject foundBeacon, out Vector2 foundLocalPos)
    {
        // In pixels
        const float BeaconSnapRange = 32f;
        float nearestValue = float.MaxValue;
        foundLocalPos = Vector2.Zero;
        foundBeacon = default;

        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleBeaconObject beaconObj)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beaconObj.Coordinates));

            if (beaconCoords.MapId != ViewingMap)
                continue;

            // Invalid beacon?
            if (!_shuttles.CanFTLBeacon(beaconObj.Coordinates))
                continue;

            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with {Y = -position.Y});

            // If beacon not on screen then ignore it.
            if (!area.Contains(localPos.Floored()))
                continue;

            var distance = (localPos - mousePos).Length();

            if (distance > BeaconSnapRange * UIScale ||
                distance > nearestValue)
            {
                continue;
            }

            foundLocalPos = localPos;
            nearestValue = distance;
            foundBeacon = beaconObj;
        }

        return foundBeacon != default;
    }

    /// <summary>
    /// Sets the map objects for the next draw.
    /// </summary>
    public void SetMapObjects(Dictionary<MapId, List<IMapObject>> mapObjects)
    {
        _mapObjects.Clear();

        if (mapObjects.TryGetValue(ViewingMap, out var obbies))
        {
            _mapObjects.AddRange(obbies);
        }
    }
}
