- type: rank
  id: RatRankKommandantSenior
  name: Гранд-адмирал
  prefix: Гранд-адмирал
  paygrade: O8

- type: rank
  id: RatRankKommandantMiddle
  name: Адмирал
  prefix: Адмирал
  paygrade: O7

- type: rank
  id: RatRankKommandantJunior
  name: Контр-адмирал
  prefix: Контр-адмирал
  paygrade: O6

