using System.Numerics;
using Content.Shared._Rat.RoundEndCredits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Rat.RoundEndCredits;

[GenerateTypedNameReferences]
public sealed partial class RoundEndCreditsWindow : DefaultWindow
{
    private readonly IEntityManager _entManager;
    private float _scrollOffset;
    private readonly float _scrollSpeed = 50f;
    private readonly float _totalHeight;
    private bool _creditsFinished;
    private float _elapsed;

    private readonly Font _titleFont;
    private readonly Font _headerFont;
    private readonly Font _bodyFont;
    private readonly Font _smallFont;

    private readonly List<SpriteView> _spriteViews = new();
    private readonly List<(Control Control, float YOffset)> _fadeControls = new();

    private static readonly Direction[] RotationDirs =
    {
        Direction.South, Direction.SouthWest, Direction.West, Direction.NorthWest,
        Direction.North, Direction.NorthEast, Direction.East, Direction.SouthEast,
    };

    public RoundEndCreditsWindow(List<CreditsPlayerInfo> players, IEntityManager entManager)
    {
        RobustXamlLoader.Load(this);
        _entManager = entManager;

        var cache = IoCManager.Resolve<IResourceCache>();
        _titleFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Bold.ttf"), 28);
        _headerFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Bold.ttf"), 20);
        _bodyFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/Cambria.ttf"), 14);
        _smallFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/Cambria.ttf"), 12);

        Background.PanelOverride = new StyleBoxFlat(Color.Black);
        CloseButton.Visible = false;

        var childOffset = 0f;

        // === TITLE ===
        AddSeparatorLine(ref childOffset);
        AddCenteredLabel(Loc.GetString("round-end-credits-title"), Color.FromHex("#CC0000"), 2f, ref childOffset);
        AddSpacing(12, ref childOffset);
        AddCenteredLabel(Loc.GetString("round-end-credits-subtitle"), Color.FromHex("#AAAAAA"), 1f, ref childOffset);
        AddSeparatorLine(ref childOffset);
        AddSpacing(40, ref childOffset);

        // === PARTICIPANTS HEADER ===
        AddSeparatorLine(ref childOffset);
        AddCenteredLabel(Loc.GetString("round-end-credits-participants"), Color.FromHex("#DDDDDD"), 1.5f, ref childOffset);
        AddSeparatorLine(ref childOffset);
        AddSpacing(30, ref childOffset);

        // === PLAYER ENTRIES ===
        foreach (var player in players)
        {
            var entry = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Center,
                SeparationOverride = 16,
                Modulate = Color.White.WithAlpha(0f),
            };

            if (player.Entity != null)
            {
                var sprite = new SpriteView(player.Entity.Value, _entManager)
                {
                    OverrideDirection = Direction.South,
                    SetSize = new Vector2(64, 64),
                    VerticalAlignment = VAlignment.Center,
                    Stretch = SpriteView.StretchMode.Fill,
                };
                _spriteViews.Add(sprite);
                entry.AddChild(sprite);
            }

            var playerLabel = new Label
            {
                Text = player.PlayerName,
                FontColorOverride = Color.White,
                FontOverride = _bodyFont,
                VerticalAlignment = VAlignment.Center,
            };
            entry.AddChild(playerLabel);

            _fadeControls.Add((entry, childOffset));
            CreditsContainer.AddChild(entry);
            childOffset += 80;

            AddThinSeparator(ref childOffset);
            AddSpacing(10, ref childOffset);
        }

        // === BOTTOM SEPARATOR ===
        AddSpacing(50, ref childOffset);
        AddSeparatorLine(ref childOffset);
        AddSpacing(20, ref childOffset);

        _totalHeight = 800 + childOffset + 800;
    }

    private void AddCenteredLabel(string text, Color color, float scale, ref float offset)
    {
        Font font;
        if (scale > 1.5f)
            font = _titleFont;
        else if (scale > 1f)
            font = _headerFont;
        else
            font = _bodyFont;

        var label = new Label
        {
            Text = text,
            FontColorOverride = color,
            FontOverride = font,
            HorizontalAlignment = HAlignment.Center,
        };
        CreditsContainer.AddChild(label);
        offset += font.GetHeight(1f) + 4;
    }

    private void AddSeparatorLine(ref float offset)
    {
        var line = new PanelContainer
        {
            MinHeight = 1,
            MaxHeight = 1,
            MinWidth = 500,
            HorizontalAlignment = HAlignment.Center,
            PanelOverride = new StyleBoxFlat(Color.FromHex("#444444")),
            Margin = new Thickness(0, 16, 0, 16),
        };
        CreditsContainer.AddChild(line);
        offset += 33;
    }

    private void AddTeamMember(string name, string role, ref float offset)
    {
        var entry = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            SeparationOverride = 12,
        };

        var nameLabel = new Label
        {
            Text = name,
            FontColorOverride = Color.White,
            FontOverride = _bodyFont,
        };

        var roleLabel = new Label
        {
            Text = "— " + role,
            FontColorOverride = Color.FromHex("#999999"),
            FontOverride = _smallFont,
        };

        entry.AddChild(nameLabel);
        entry.AddChild(roleLabel);
        CreditsContainer.AddChild(entry);
        offset += 24;
    }

    private void AddThinSeparator(ref float offset)
    {
        var line = new PanelContainer
        {
            MinHeight = 1,
            MaxHeight = 1,
            MinWidth = 200,
            HorizontalAlignment = HAlignment.Center,
            PanelOverride = new StyleBoxFlat(Color.FromHex("#333333")),
            Margin = new Thickness(0, 8, 0, 8),
        };
        CreditsContainer.AddChild(line);
        offset += 17;
    }

    private void AddSpacing(float height, ref float offset)
    {
        CreditsContainer.AddChild(new Control { MinHeight = height });
        offset += height;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _elapsed += args.DeltaSeconds;
        _scrollOffset += _scrollSpeed * args.DeltaSeconds;

        TopSpacer.MinHeight = Math.Max(0, 800 - _scrollOffset);

        // Rotate sprites through directions
        var dirIndex = (int)(_elapsed * 2f) % RotationDirs.Length;
        foreach (var sprite in _spriteViews)
        {
            sprite.OverrideDirection = RotationDirs[dirIndex];
        }

        // Fade-in player entries as they scroll into view
        var viewTop = _scrollOffset - 800;
        foreach (var (control, yOff) in _fadeControls)
        {
            var dist = viewTop - yOff + 400;
            var alpha = Math.Clamp(dist / 200f, 0f, 1f);
            control.Modulate = Color.White.WithAlpha(alpha);
        }

        if (_scrollOffset >= _totalHeight && !CloseButton.Visible)
        {
            CloseButton.Visible = true;
            _creditsFinished = true;
        }
    }

    public void ForceClose()
    {
        _creditsFinished = true;
        base.Close();
    }

    public override void Close()
    {
        if (!_creditsFinished)
            return;

        base.Close();
    }
}
