using Content.Shared._Rat.Diplomacy;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Rat.Diplomacy;

[GenerateTypedNameReferences]
public sealed partial class DiplomacyConsoleMenu : DefaultWindow
{
    private static readonly string[] AllFactions =
        ["DSM", "NCWL", "SHI", "SRM", "TAP", "IPM", "SAW", "GSC", "CD", "TSP"];

    private static readonly Color WarBg = Color.FromHex("#6B1A1A");
    private static readonly Color AllyBg = Color.FromHex("#1A4D2E");
    private static readonly Color PeaceBg = Color.FromHex("#1A3D4D");
    private static readonly Color NeutralBg = Color.FromHex("#2A2A2E");

    public event Action<string>? OnDeclareWar;
    public event Action<string>? OnProposePeace;
    public event Action<string>? OnProposeAlliance;
    public event Action<string>? OnProposeTrade;
    public event Action<string>? OnBreakTrade;
    public event Action<string, PendingProposalType>? OnAcceptProposal;
    public event Action<string, PendingProposalType>? OnRejectProposal;

    public DiplomacyConsoleMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(DiplomacyConsoleBoundUserInterfaceState state)
    {
        PendingContainer.RemoveAllChildren();
        if (state.PendingProposals.Count == 0)
        {
            PendingContainer.AddChild(new Label
            {
                Text = Loc.GetString("diplomacy-no-proposals"),
                FontColorOverride = Color.Gray,
                Margin = new Thickness(4, 2)
            });
        }
        else
        {
            foreach (var proposal in state.PendingProposals)
                PendingContainer.AddChild(BuildPendingRow(proposal));
        }

        RelationsContainer.RemoveAllChildren();

        var myLabel = new PanelContainer { MinHeight = 28 };
        myLabel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1C1C22") };
        var myRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(6, 4) };
        myRow.AddChild(new Label
        {
            Text = Loc.GetString($"faction-{state.CurrentFactionId}"),
            FontColorOverride = Color.White,
            HorizontalExpand = true,
            SizeFlagsStretchRatio = 1.5f
        });
        myRow.AddChild(new Label
        {
            Text = Loc.GetString("diplomacy-your-faction"),
            FontColorOverride = Color.LightGreen,
            HorizontalExpand = true
        });
        myLabel.AddChild(myRow);
        RelationsContainer.AddChild(myLabel);

        foreach (var factionId in AllFactions)
        {
            if (factionId == state.CurrentFactionId)
                continue;

            var relation = state.Relations.GetValueOrDefault(factionId, FactionRelation.Neutral);
            RelationsContainer.AddChild(BuildRelationRow(factionId, relation));
        }
    }

    private Control BuildPendingRow(PendingProposal proposal)
    {
        var row = new PanelContainer { MinHeight = 28 };
        row.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1C1C22") };

        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 4),
            HorizontalExpand = true
        };

        var typeText = proposal.Type switch
        {
            PendingProposalType.Peace => Loc.GetString("diplomacy-proposal-type-peace"),
            PendingProposalType.Alliance => Loc.GetString("diplomacy-proposal-type-alliance"),
            PendingProposalType.Trade => Loc.GetString("diplomacy-proposal-type-trade"),
            _ => Loc.GetString("diplomacy-proposal-type-unknown")
        };

        inner.AddChild(new Label
        {
            Text = $"{Loc.GetString($"faction-{proposal.FromFactionId}")} → {typeText}",
            FontColorOverride = Color.White,
            HorizontalExpand = true
        });

        var acceptBtn = new Button
        {
            Text = Loc.GetString("diplomacy-accept-button"),
            MinWidth = 80
        };
        acceptBtn.OnPressed += _ => OnAcceptProposal?.Invoke(proposal.FromFactionId, proposal.Type);
        inner.AddChild(acceptBtn);

        var rejectBtn = new Button
        {
            Text = Loc.GetString("diplomacy-reject-button"),
            MinWidth = 80
        };
        rejectBtn.OnPressed += _ => OnRejectProposal?.Invoke(proposal.FromFactionId, proposal.Type);
        inner.AddChild(rejectBtn);

        row.AddChild(inner);
        return row;
    }

    private Control BuildRelationRow(string factionId, FactionRelation relation)
    {
        var bg = relation switch
        {
            FactionRelation.War => WarBg,
            FactionRelation.Alliance => AllyBg,
            FactionRelation.Peace => PeaceBg,
            FactionRelation.Trade => Color.FromHex("#1A4D3D"),
            _ => NeutralBg
        };

        var row = new PanelContainer { MinHeight = 28 };
        row.PanelOverride = new StyleBoxFlat { BackgroundColor = bg };

        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 4),
            HorizontalExpand = true
        };

        inner.AddChild(new Label
        {
            Text = Loc.GetString($"faction-{factionId}"),
            FontColorOverride = Color.White,
            HorizontalExpand = true,
            SizeFlagsStretchRatio = 1.5f
        });

        inner.AddChild(new Label
        {
            Text = Loc.GetString($"diplomacy-relation-{relation.ToString().ToLower()}"),
            FontColorOverride = Color.White,
            HorizontalExpand = true
        });

        var btnContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2
        };

        var warBtn = new Button
        {
            Text = Loc.GetString("diplomacy-button-war"),
            MinWidth = 80,
            Disabled = relation == FactionRelation.War
        };
        warBtn.OnPressed += _ => OnDeclareWar?.Invoke(factionId);
        btnContainer.AddChild(warBtn);

        var peaceBtn = new Button
        {
            Text = Loc.GetString("diplomacy-button-peace"),
            MinWidth = 90,
            Disabled = relation == FactionRelation.Peace || relation == FactionRelation.Alliance
        };
        peaceBtn.OnPressed += _ => OnProposePeace?.Invoke(factionId);
        btnContainer.AddChild(peaceBtn);

        var allyBtn = new Button
        {
            Text = Loc.GetString("diplomacy-button-alliance"),
            MinWidth = 90,
            Disabled = relation == FactionRelation.Alliance
        };
        allyBtn.OnPressed += _ => OnProposeAlliance?.Invoke(factionId);
        btnContainer.AddChild(allyBtn);

        var tradeBtn = new Button
        {
            Text = relation == FactionRelation.Trade ? Loc.GetString("diplomacy-button-break-trade") : Loc.GetString("diplomacy-button-trade"),
            MinWidth = 90
        };
        if (relation == FactionRelation.Trade)
            tradeBtn.OnPressed += _ => OnBreakTrade?.Invoke(factionId);
        else
            tradeBtn.OnPressed += _ => OnProposeTrade?.Invoke(factionId);
        btnContainer.AddChild(tradeBtn);

        inner.AddChild(btnContainer);
        row.AddChild(inner);
        return row;
    }
}
