using Content.Shared._Rat.Diplomacy;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Rat.Diplomacy;

[GenerateTypedNameReferences]
public sealed partial class FactionStatusWidget : UIWidget
{
    private static readonly string[] AllFactions =
        ["DSM", "NCWL", "SHI", "SRM", "TAP", "IPM", "SAW", "GSC", "CD", "TSP"];

    private static readonly Color WarBg = Color.FromHex("#6B1A1A");
    private static readonly Color AllyBg = Color.FromHex("#1A4D2E");
    private static readonly Color PeaceBg = Color.FromHex("#1A3D4D");
    private static readonly Color TradeBg = Color.FromHex("#1A4D3D");
    private static readonly Color NeutralBg = Color.FromHex("#2A2A2E");
    private static readonly Color HeaderBg = Color.FromHex("#111116");

    public FactionStatusWidget()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateRelations(string myFaction, Dictionary<string, FactionRelation> relations)
    {
        RowsContainer.RemoveAllChildren();

        var header = new PanelContainer { MinHeight = 20 };
        header.PanelOverride = new StyleBoxFlat { BackgroundColor = HeaderBg };
        header.AddChild(new Label
        {
            Text = Loc.GetString($"faction-{myFaction}"),
            FontColorOverride = Color.LightGreen,
            Margin = new Thickness(4, 2),
            HorizontalAlignment = HAlignment.Right
        });
        RowsContainer.AddChild(header);

        foreach (var factionId in AllFactions)
        {
            if (factionId == myFaction)
                continue;

            var relation = relations.GetValueOrDefault(factionId, FactionRelation.Neutral);

            var bg = relation switch
            {
                FactionRelation.War => WarBg,
                FactionRelation.Alliance => AllyBg,
                FactionRelation.Peace => PeaceBg,
                FactionRelation.Trade => TradeBg,
                _ => NeutralBg
            };

            var row = new PanelContainer { MinHeight = 18 };
            row.PanelOverride = new StyleBoxFlat { BackgroundColor = bg };

            var inner = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(4, 1)
            };

            inner.AddChild(new Label
            {
                Text = Loc.GetString($"faction-{factionId}"),
                FontColorOverride = Color.White,
                HorizontalExpand = true,
                MinWidth = 80
            });

            inner.AddChild(new Label
            {
                Text = Loc.GetString($"diplomacy-relation-short-{relation.ToString().ToLower()}"),
                FontColorOverride = Color.White,
                HorizontalAlignment = HAlignment.Right,
                MinWidth = 28
            });

            row.AddChild(inner);
            RowsContainer.AddChild(row);
        }
    }

    public void Clear()
    {
        RowsContainer.RemoveAllChildren();
    }
}
