# CMM Ranks
- type: rank
  id: RatRankCMMMarshalHigh
  name: Секториальный маршал
  prefix: Сект. маршал
  paygrade: CMM-C5

- type: rank
  id: RatRankCMMMarshalLead
  name: Старший маршал
  prefix: Ст. маршал
  paygrade: CMM-C4

- type: rank
  id: RatRankCMMMarshalSenior
  name: Маршал
  prefix: Маршал
  paygrade: CMM-C3

- type: rank
  id: RatRankCMMMarshalMiddle
  name: 2й Маршал
  prefix: 2й Маршал
  paygrade: CMM-C2

- type: rank
  id: RatRankCMMMarshalJunior
  name: Майор ополчения
  prefix: Майор
  paygrade: CMM-C1

- type: rank
  id: RatRankCMMMinutemanTop
  name: Капитан ополчения
  prefix: Капитан
  paygrade: CMM10

- type: rank
  id: RatRankCMMMinutemanFirst
  name: 1й Лейтенант ополчения
  prefix: 1й Лейт.
  paygrade: CMM9

- type: rank
  id: RatRankCMMMinutemanSecond
  name: 2й Лейтенант ополчения
  prefix: 2й Лейт.
  paygrade: CMM8

- type: rank
  id: RatRankCMMMinutemanThird
  name: Комендор-сержант ополчения
  prefix: Ком.-серж.
  paygrade: CMM7

- type: rank
  id: RatRankCMMMinutemanSrLead
  name: Штаб-сержант ополчения
  prefix: Штаб-сержант
  paygrade: CMM6

- type: rank
  id: RatRankCMMMinutemanLead
  name: Сержант ополчения
  prefix: Сержант
  paygrade: CMM5

- type: rank
  id: RatRankCMMMinutemanSenior
  name: Капрал ополчения
  prefix: Капрал
  paygrade: CMM4

- type: rank
  id: RatRankCMMMinutemanMiddle
  name: Младший капрал ополчения
  prefix: Мл. капрал
  paygrade: CMM3

- type: rank
  id: RatRankCMMMinutemanJunior
  name: Рядовой ополчения первого класса
  prefix: Рядовой 1го кл.
  paygrade: CMM2

- type: rank
  id: RatRankCMMMinutemanNovice
  name: Рядовой ополчения
  prefix: Рядовой
  paygrade: CMM1