using System;
using Content.Shared._Rat.AlertConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.AlertConsole;

[GenerateTypedNameReferences]
public sealed partial class AlertConsoleMenu : DefaultWindow
{
    public event Action<AlertConsoleBuiState>? OnSavePressed;

    public AlertConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        RadiusSlider.OnValueChanged += _ =>
            RadiusValueLabel.Text = $"{(int) RadiusSlider.Value} м";

        CooldownSlider.OnValueChanged += _ =>
            CooldownValueLabel.Text = $"{(int) CooldownSlider.Value} сек";

        BroadcastCheck.OnToggled += args =>
            ShuttleMessageEdit.Editable = args.Pressed;

        SaveButton.OnPressed += _ =>
        {
            OnSavePressed?.Invoke(new AlertConsoleBuiState(
                EnabledCheck.Pressed,
                RadiusSlider.Value,
                string.Empty,
                false,
                StationMessageEdit.Text,
                BroadcastCheck.Pressed,
                ShuttleMessageEdit.Text,
                CooldownSlider.Value));
        };
    }

    public void UpdateState(AlertConsoleBuiState state)
    {
        EnabledCheck.Pressed = state.Enabled;

        RadiusSlider.SetValueWithoutEvent(Math.Clamp(state.DetectionRadius, 10f, 2000f));
        RadiusValueLabel.Text = $"{(int) state.DetectionRadius} м";

        ChannelLabel.Text = state.FactionChannelResolved
            ? Loc.GetString("alert-console-channel-value", ("channel", state.FactionChannel))
            : Loc.GetString("alert-console-channel-unknown");

        CooldownSlider.SetValueWithoutEvent(Math.Clamp(state.AlertCooldownSeconds, 5f, 3600f));
        CooldownValueLabel.Text = $"{(int) state.AlertCooldownSeconds} сек";

        StationMessageEdit.Text = state.StationAlertMessage;

        BroadcastCheck.Pressed = state.BroadcastToShuttle;
        ShuttleMessageEdit.Text = state.ShuttleAlertMessage;
        ShuttleMessageEdit.Editable = state.BroadcastToShuttle;
    }
}
