- type: faction
  name: "Божественный Мандат Солнца"
  id: DSM
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: НЕТ
    Одна из двух основных сил в секторе Тайпан.
    Подходит для новых игроков и отражает основной опыт игры на сервере.
  buttonColor: DarkSlateBlue
  description: |
    Нео-феодальный осколок Империи, когда-то простиравшейся через звёзды, во многом схожий с древней Священной Римской империей.​
    Теперь её остатки в основном изолированы в этом секторе. По воле божественного кайзера силы Мандата были посланы сюда, чтобы
    обезопасить сектор от социалистической заразы, ныне известная как Лига Рабочих Нового Полумесяца.​ На протяжении десятилетий
    эти два гиганта сталкивались в борьбе за контроль над Сектором, чередуя победы и поражения. Авианосец под названием «Ревизор»
    выходит в Тайпан, чтобы закрепиться и вновь выбить дать отпор ЛРНП.

    Божественный Мандат Солнца возносит молитвы святым и, прежде всего, кайзеру, прося у них победы.​ Большинство высоких должностей
    занимают члены знатных домов с разным статусом внутри Мандата, а на вершине стоит Дом Кирхайс. Дом Вопросов держит слуг Мандата
    в постоянной настороженности, быстро реагируя на любые признаки нелояльности или измены. Свободные держатели или даже
    аристократы, которые решают выступить против нынешнего режима, вскоре оказываются под пристальным наблюдением Дома Вопросов,
    испытывая давление, вынуждающее их замолчать, а порой и вовсе исчезая бесследно. Другим расам разрешено служить в Имперских
    рядах, но к ним часто относятся с повышенным подозрением и подвергают формальной или неформальной дискриминации. Особенно от
    этого страдают нианы, над которыми потешаются даже унатхи.
  color: "#9FED58"
  weight: 8
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: dsm

- type: faction
  name: "Лига Рабочих Нового Полумесяца"
  id: NCWL
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: НЕТ
    Одна из двух основных сил в секторе Тайпан.
    Подходит для новых игроков и отражает основной опыт игры на сервере.
  buttonColor: "#a46106"
  description: |
    Воинствующее синдикалистское правительство, рождённое в результате восстания  против Дома Оливир. Теперь оно превратилось в
    одну из главных сил изолированного сектора, способную соперничать с Божественным Мандатом Солнца. Они действуют с их передовой
    станции, Порт Марсова, ведя многолетнюю войну против имперских войск, жаждущих вновь поработить их. Они состоят из нескольких
    Рабочих профсоюзов, но на фронте сражаются члены Ополчения, возглавляемые железной волей Волгина Гришинграда.

    Лига Рабочих Нового Полумесяца стремится к равенству и свободе для всех работников Полумесяца, независимо от их вида. Их
    убеждения закалились под гнётом жёстких квот дома Оливир и подавления профсоюзов. В какой-то момент Лиге удалось освободить
    весь Сектор, окончательно свергнув дом Оливир, но эта победа оказалась недолгой: многие достижения были перечёркнуты с
    прибытием дома Кирхайс. После многих лет войны в системе наконец появляются трещины, но немногие существующие диссиденты
    не решаются высунуться, опасаясь, что их задержит Министерство внутренней бдительности и дисциплины.

  color: "#9FED58"
  weight: 7
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: ncwl

- type: faction
  name: "«Шиногара» Тяжёлая Промышленность"
  id: SHI
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 3 ЧАСА / 1 РАУНД
    Промышленный гигант с геймплеем, завязанным на торговле и высоких технологиях.
    Ожидайте жёстких норм по прибыли, пиратских рейдов и минимальной поддержки.
  buttonColor: DarkSlateGray
  description: |
    Последний оставшийся корпоративный гигант. Напоминание и реликт старого мира. Тяжёлая Промышленность «Шиногара» — последняя
    «настоящая корпорация» в нынешнее время. Отрезанные от основной области, где они властвуют над огромным массивом пространства
    под вывеской Нового Американского протектората, их корпоративная догма остаётся неизменной. Происходя из эпохи, когда миром
    правили корпорации - мира непревзойдённой жадности, инноваций, прогресса и эффективности. Для большинства методы Shinohara
    кажутся более «чуждыми», чем многие инопланетные виды. Будучи крупнейшим игроком в сфере аркеотехнологий, корпорация владеет
    множеством заново открытых и обратным инжинирингом переработанных технологий ныне не существующей NanoTrasen Industries, что
    делает ТПШ непревзойдённой корпоративной сверхдержавой в Секторе.​

    Они управляют логистикой между системами, сбором технологий, добычей ресурсов и даже занимаются производством космических
    кораблей. Хотя в основном они действуют со Судоверфей «Прометей», «Тацумото» используется для представления их интересов
    и продажи их товаров всем сторонам. Расположенный в оспариваемой системе между Лигой и Мандатом, включая присутствие Коалиции
    Свободных Станций Тайпани, Шинодара была вынуждена вступить в спираль «Стратегических торговых отношений», «Кинетического
    сохранения корпоративных интересов» и «Управления конкурентным партнёрством».
  color: "#9FED58"
  weight: 5
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: shi

- type: faction
  name: "Коалиция Вольных Станцией Тайпана"
  id: TFSC
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 3 ЧАСА / 1 РАУНД
    Четыре отдельных корпорации, объединённые под одним флагом ради прибыли и свободы.
    Другие фракции могут предлагать контракты или просить об услугах.
    Другие фракции могут относиться с подозрением или быть сразу враждебны.
    Ваши союзники могут предать вас ради более высокой выплаты.
  buttonColor: DarkRed
  description: |
    Свободное объединение независимых групп, состоящее из пиратов, каперов, кораблеломщиков и хищных медицинских специалистов,
    почти не имеющих угрызений совести при изъятии ваших органов для себя. Наиболее заметные группы: Gorlex Security Consulting,
    Interdyne Pharmaceuticals, Cyberdawn Technologies и Shipfitters Astronautics Workers Union. Каждая из них предлагает
    определённые услуги и извлекает из них прибыль. Иногда их сравнивают с падальщичьей экосистемой за то, как они действуют.

    Они родились из старого Нового Синдиката Каперов Полумесяца, фракции, сформированной перебежчиками из Мандата и Лиги, желавшими
    жить вне хватки крупных фракций. В основном это были пираты и каперы, к которым крупные игроки в секторе относились
    недоброжелательно и беспощадно охотились на них. Те каперы, что видели приближающийся конец, сформировали Коалицию
    Свободных Станций Тайпани, сделав акцент скорее на предоставлении своего разнообразного спектра услуг, чем на простомграбеже.
    Но с уничтожением Либерталия эти группы разошлись ещё дальше, часто воюя друг с другом.
  color: "#9FED58"
  weight: 6
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tfsc

- type: faction
  name: "Тайпано-Атирийский Пакт"
  id: TAP
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ ИГРЫ: 10 ЧАСОВ / 3 РАУНДА
    У этой фракции есть лишь очень маленький аванпост в системе Тайпан.
    Их присутствие ограничено маленькой, скрытой станцией всего с четырьмя ролями.
    Играйте на свой страх и риск.
  buttonColor: DarkGreen
  description: |
    Свободно организованная племенная община кочевых звёздных странников, Тайпано-Атирийский Пакт состоит из нескольких кочевых
    семей разного расового происхождения. Они действуют с переоборудованного капитального грузового корабля, перемещаясь от
    места к месту, чтобы заработать на жизнь. Большинство кочевников имеют дурную славу наёмников, подонков, контрабандистов,
    рэкетиров и игроков.
  color: "#9FED58"
  weight: 4
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: fourfamilies

- type: faction
  name: "Ополчение Святого Ромейна"
  id: SRM
  descriptionPrefix: |
    МИНИМАЛЬНОЕ ВРЕМЯ: 10 ЧАСОВ / 3 РАУНДА
    Эта фракция очень редко присутствует в системе Тайпан.
    Ограничены особыми мидраунд спавнами
  buttonColor: "#001d18"
  description: |
    Когда-то несколько огневых команд Имперского корпуса подчинения были объединены под одним крылом,
    но теперь Великая Охота обрела свою новую сущность в возвращении сбежавших имперских "активов",
    а также в "призыве на военную службу" новых. По сути, это гильдия работорговцев
    с самозваным божественным превосходством, они действуют за пределами системы Доменов под
    руководством своих имперских повелителей, но часто забредают на Тайпан, чтобы захватить
    жертв для восстановления.

    Фанатики Святого Ромейна, которые не желают ничего, кроме крови атирийцев. Однако в наши дни
    кажется, что они проводят больше времени, прячась в тумане, чем выслеживая свою добычу.
    Вы все равно должны быть осторожны во время их Охоты, если вы не человек - они не склонны к милосердию.
  color: "#9FED58"
  weight: 3
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: srm

- type: faction
  name: "Central Sol Authority"
  id: ATH
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction is only very rarely present in the Taypan system.
    Restricted to Special Midround Spawns
  buttonColor: "#ffbf00"
  description: |
    An oligarchic authoritarian regime, the successor state to the old Mandate, that could now be best described as fascist.
    They are held responsible for the death of the old Kaiser and have been fighting a civil war for decades.
    Often known as simply the Authoritat, they were born out of the greed of the former Imperial court. Led by the Jovian
    ideals of psionic purity, the Authoritat has minimal interest in feudal reign like their precursors, instead focusing on
    controlling the populace and on violent conquests made to eradicate species and communities that they've found to be linked
    to the Boundary, Taypan, and other psionic phenomena. It is believed by Authoritat officials that the source of the
    Boundary itself comes from the combined, manifested thought of all psionically-enabled people in the Imperial Supercluster,
    and with every spell cast, every psionicist born, it only becomes larger and more aggressive, threatening to consume the galaxy.

    Effectively, the prime superpower of all of humanity, the Authoritat allows for a good amount of economic freedom for its
    non-psionic populace and promotes loyalty in a manner not too dissimilar to the Prussian traditions of old Earth,
    with aspiring members climbing up the military ladder of different units, such as the 43rd Battlegroup of the Sol system.
    Dissenters who think they can speak up against the current regime quickly find themselves screened and detained.
    Tight information control prevents widespread dissent, and officials often rewrite history itself to suit the needs of the
    Authoritat.
  color: "#ffffed"
  weight: 2
  enabled: false
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: csa

- type: faction
  name: "Колониальное ополчение"
  id: TSP
  description: |
    Колониальное ополчение - малочисленная организация, сформировавшаяся вокруг харизматичных лидеров.
    Основанные на идеалах свободы, равноправия и американской мечты, они принимают под своё крыло космонавтов
    и беженцев со всей системы, давая им дом и место для отдыха, взамен принимая конфискованную контрабанду
    или снаряжение для оснащения отрядов ополчения. Расположенные на вольной торговой станции Глисс-Санто,
    они находятся под управлением колониального маршала, координирующего отряды ополчения во всей системе, и управляющего станцией.
  color: "#9FED58"
  weight: 1
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tsp