using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client._Goobstation.UserInterface.Systems.Ghost.Controls;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }
    public GhostBarRulesWindow GhostBarWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? ReturnToRoundPressed;
    public event Action? InsuranceRespawnPressed;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        GhostBarWindow = new GhostBarRulesWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        ReturnToRound.OnPressed += _ => ReturnToRoundPressed?.Invoke();
        InsuranceRespawnButton.OnPressed += _ => InsuranceRespawnPressed?.Invoke();
    }

    public void Hide()
    {
        TargetWindow.Close();
        GhostBarWindow.Close(); // Goobstation - Ghost Bar
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));
            if (roles > 0)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonDanger);
            }
            else
            {
                GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonDanger);
            }
        }

        TargetWindow.Populate();
    }

    public void UpdateInsuranceRespawn(bool available, TimeSpan timeLeft, bool spawnMachineReady = true)
    {
        InsuranceRespawnButton.Visible = available;
        if (!available)
            return;

        var timerReady = timeLeft <= TimeSpan.Zero;
        var ready = timerReady && spawnMachineReady;
        InsuranceRespawnButton.Disabled = !ready;
        if (timerReady && !spawnMachineReady)
        {
            InsuranceRespawnButton.Text = Loc.GetString("ghost-gui-insurance-respawn-no-machine");
            return;
        }

        InsuranceRespawnButton.Text = timerReady
            ? Loc.GetString("ghost-gui-insurance-respawn-ready")
            : Loc.GetString("ghost-gui-insurance-respawn-timer", ("time", $"{timeLeft.Minutes:D2}:{timeLeft.Seconds:D2}"));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
            GhostBarWindow.Dispose(); // Goobstation - Ghost Bar
        }
    }
}
