using Content.Shared._Rat.DnaDatabase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.DnaDatabase;

[GenerateTypedNameReferences]
public sealed partial class DnaDatabaseWindow : DefaultWindow
{
    public event Action? OnToggle;

    public DnaDatabaseWindow()
    {
        RobustXamlLoader.Load(this);
        ToggleButton.OnPressed += _ => OnToggle?.Invoke();
    }

    public void UpdateState(DnaDatabaseBoundUserInterfaceState state)
    {
        FactionLabel.Text = Loc.GetString("dna-database-faction", ("faction", state.FactionName));

        StatusLabel.Text = state.Enabled
            ? Loc.GetString("dna-database-status-online")
            : Loc.GetString("dna-database-status-offline");

        JobsLabel.Text = state.UnlimitedJobs > 0
            ? Loc.GetString("dna-database-jobs-with-unlimited",
                ("available", state.AvailableJobs),
                ("total", state.TotalJobs),
                ("unlimited", state.UnlimitedJobs))
            : Loc.GetString("dna-database-jobs",
                ("available", state.AvailableJobs),
                ("total", state.TotalJobs));

        ToggleButton.Text = state.Enabled
            ? Loc.GetString("dna-database-disable")
            : Loc.GetString("dna-database-enable");
    }
}
