# SHI Ranks
## SHI - Executive
- type: rank
  id: RatRankSHIExecutiveTop
  name: Исполнительный директор
  prefix: Сёитии
  paygrade: SHI-E6

- type: rank
  id: RatRankSHIExecutiveHigh
  name: Секториальный директор
  prefix: Дзюитии
  paygrade: SHI-E5

- type: rank
  id: RatRankSHIExecutiveLead
  name: Директор
  prefix: Сёнии
  paygrade: SHI-E4

- type: rank
  id: RatRankSHIExecutiveSenior
  name: Заместитель директора
  prefix: Джичо
  paygrade: SHI-E3

- type: rank
  id: RatRankSHIExecutiveMiddle
  name: Секториальный менеджер
  prefix: Качо
  paygrade: SHI-E2

- type: rank
  id: RatRankSHIExecutiveJunior
  name: Менеджер
  prefix: Какаричо
  paygrade: SHI-E1

## SHI - Board
- type: rank
  id: RatRankSHIBoardTop
  name: Главный корпоративный исполнитель
  prefix: Дзюсии
  paygrade: SHI-B6

- type: rank
  id: RatRankSHIBoardHigh
  name: Супервайзер корпорации
  prefix: Хатиигэ
  paygrade: SHI-B5

- type: rank
  id: RatRankSHIBoardLead
  name: Исполнительный специалист корпорации
  prefix: Рокуигэ
  paygrade: SHI-B4

- type: rank
  id: RatRankSHIBoardSenior
  name: Старший корпоративный исполнитель
  prefix: Кё То
  paygrade: SHI-B3

- type: rank
  id: RatRankSHIBoardMiddle
  name: Корпоративный исполнитель
  prefix: Ке Ю
  paygrade: SHI-B2

- type: rank
  id: RatRankSHIBoardJunior
  name: Младший корпоративный исполнитель
  prefix: Ко Си
  paygrade: SHI-B1

## SHI - MedTech
- type: rank
  id: RatRankSHIMedTechLead
  name: Ведущий исследователь корпорации
  prefix: Дзюдан
  paygrade: SHI-R4

- type: rank
  id: RatRankSHIMedTechHigh
  name: Старший исследователь корпорации
  prefix: Тэнгэн
  paygrade: SHI-R3

- type: rank
  id: RatRankSHIMedTechMiddle
  name: Исследователь корпорации
  prefix: Одза
  paygrade: SHI-R2

- type: rank
  id: RatRankSHIMedTechJunior
  name: Младший исследователь корпорации
  prefix: Госэй
  paygrade: SHI-R1

## SHI - Workers
- type: rank
  id: RatRankSHIWorkerLead
  name: Ведущий сотрудник корпорации
  prefix: Вакасигара
  paygrade: SHI-W4

- type: rank
  id: RatRankSHIWorkerHigh
  name: Старший сотрудник корпорации
  prefix: Вакашу
  paygrade: SHI-W3

- type: rank
  id: RatRankSHIWorkerMiddle
  name: Сотрудник корпорации
  prefix: Сятэй
  paygrade: SHI-W2

- type: rank
  id: RatRankSHIWorkerJunior
  name: Корпоративный стажёр
  prefix: Стажёр
  paygrade: SHI-W1

## SHI - CorpSec
- type: rank
  id: RatRankSHICorpSecChief
  name: Начальник корпоративной службы безопасности
  prefix: Кайгун Тюса
  paygrade: SHI-CS6

- type: rank
  id: RatRankSHICorpSecHigh
  name: Руководитель отдела корпоративной службы безопасности
  prefix: Кайгун Тайса
  paygrade: SHI-CS5

- type: rank
  id: RatRankSHICorpSecLead
  name: Ведущий сотрудник корпоративной службы безопасности
  prefix: Гунбугён
  paygrade: SHI-CS4

- type: rank
  id: RatRankSHICorpSecSenior
  name: Старший сотрудник корпоративной службы безопасности
  prefix: Бансё
  paygrade: SHI-CS3

- type: rank
  id: RatRankSHICorpSecMiddle
  name: Сотрудник корпоративной службы безопасности
  prefix: Сёмё
  paygrade: SHI-CS2

- type: rank
  id: RatRankSHICorpSecJunior
  name: Кадет корпоративной службы безопасности
  prefix: Кадет
  paygrade: SHI-CS1