- type: job
  id: planetfall_mvdofficer
  name: job-name-ncwl-mvd-officer
  description: job-description-ncwl-mvd-officer
  playTimeTracker: JobMVDOfficerNCWL
  weight: 100
  startingGear: planetfall_mvdofficer_gear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconUnionfallNCWLCaptain"
  chatNameColor: "#a11515"
  chatAmplification:
    bubbleScale: 1.08
    shoutBubbleScale: 1.3
    radioScale: 1.2
    radioBold: true
  supervisors: job-supervisors-ncwl-mvd
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 100000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
          - Tradeband
        addUnderstood:
          - Dockta
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: planetfall_mvdofficer_gear
  equipment:
    shoes: ClothingShoesBootsMVDParade
    jumpsuit: ClothingUniformJumpsuitMVD
    id: NCWLMVDLeaderPDA
    outerClothing: ClothingOuterArmorMVDCoat
    pocket1: WeaponRevolverPythonSecurity
    back: ClothingBackpackNCWL
    belt: ClothingBeltSheathNCWLKukriFilled
    eyes: ClothingEyesGlassesSecurity
    suitstorage: WeaponSniperMolot
    gloves: ClothingHandsGlovesMVD
    head: ClothingHeadHatAuthorityKommandant
    ears: ClothingHeadsetNCWLCommand_Planetfall
    pocket2: FlippoEngravedLighter
  storage:
    back:
    - MagazineCaselessRifle
    - CigarNCWLCase
    - BookOfKane
