- type: job
  id: RingleaderNCSP
  name: job-name-ringleader
  description: job-description-ringleader
  playTimeTracker: JobRingleaderNCSP
  weight: 12
  startingGear: RingleaderGear
  alwaysUseSpawner: true
  whitelisted: true # Rat
  requireAdminNotify: true
  icon: "JobIconSyndieRingleader"
  supervisors: job-supervisors-gsc-ringleader
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-synadmin
      - type: HullrotFaction
        faction: GSC
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - Tradeband
        addUnderstood:
          - Freespeak
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - SyndicateBasic
  - SyndicateCommand
  - SyndicateRingleader
  - SyndicateFunds
  - SyndicateGorlex

- type: startingGear
  id: RingleaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatSyndicateOfficer
    outerClothing: ClothingOuterArmorSyndicateRingmaster
    id: RingleaderPDA
    ears: ClothingHeadsetNCSPCommand
    gloves: ClothingHandsGlovesFingerless
    belt: AccessElevatorGSC
    pocket1: WeaponPistolDeagleUranium
    pocket2: WeaponPistolDeagleUranium
    mask: ClothingMaskGasSyndicate
    back: ClothingBackpackSatchelLeatherFilledNCWLAdministrator
  storage:
    back:
      - RatRubberStampTFSCGorlex
