- type: rank
  id: RatRankNCWLEnlistedTop
  name: Старший прапорщик
  prefix: Ст. прап.
  paygrade: E8

- type: rank
  id: RatRankNCWLEnlistedBased
  name: Прапорщик
  prefix: Прапорщик
  paygrade: E7

- type: rank
  id: RatRankNCWLEnlistedHigh
  name: Старшина
  prefix: Старшина
  paygrade: E6
  
- type: rank
  id: RatRankNCWLEnlistedLead
  name: Старший сержант
  prefix: Ст. серж.
  paygrade: E5

- type: rank
  id: RatRankNCWLEnlistedSenior
  name: Сержант
  prefix: Сержант
  paygrade: E4

- type: rank
  id: RatRankNCWLEnlistedMiddle
  name: Младший сержант
  prefix: Мл. серж.
  paygrade: E3

- type: rank
  id: RatRankNCWLEnlistedJunior
  name: Ефрейтор
  prefix: Ефрейтор
  paygrade: E2

- type: rank
  id: RatRankNCWLEnlistedNovice
  name: Рядовой
  prefix: Рядовой
  paygrade: E1
