- type: rank
  id: RatRankNCWLOfficerTop
  name: Полковник
  prefix: Полковник
  paygrade: O7

- type: rank
  id: RatRankNCWLOfficerHigher
  name: Подполковник
  prefix: Подполковник
  paygrade: O6

- type: rank
  id: RatRankNCWLOfficerHigh
  name: Майор
  prefix: Майор
  paygrade: O5

- type: rank
  id: RatRankNCWLOfficerLead
  name: Капитан
  prefix: Капитан
  paygrade: O4

- type: rank
  id: RatRankNCWLOfficerSenior
  name: Старший лейтенант
  prefix: Ст. лейт.
  paygrade: O3

- type: rank
  id: RatRankNCWLOfficerMiddle
  name: Лейтенант
  prefix: Лейтенант
  paygrade: O2

- type: rank
  id: RatRankNCWLOfficerJunior
  name: Младший лейтенант
  prefix: Мл. лейт.
  paygrade: O1
