
# Komissariat
- type: rank
  id: RatRankKommissarLead
  name: Главный комиссар
  prefix: Гл. комиссар
  paygrade: K5

- type: rank
  id: RatRankKommissarSenior
  name: Старший комиссар
  prefix: Ст. комиссар
  paygrade: K4

- type: rank
  id: RatRankKommissarMiddle
  name: Комиссар
  prefix: Комиссар
  paygrade: K3

- type: rank
  id: RatRankKommissarJunior
  name: Младший комиссар
  prefix: Мл. комиссар
  paygrade: K2

- type: rank
  id: RatRankKommissarNovice
  name: Комиссар-кадет
  prefix: Комиссар-кадет
  paygrade: K1

## MVD

- type: rank
  id: RatRankMVDGruntLead
  name: Лейтенант МВД
  prefix: Лейт.-милиционер
  paygrade: MVD4

- type: rank
  id: RatRankMVDGruntSenior
  name: Сержант МВД	
  prefix: Серж.-милиционер
  paygrade: MVD3

- type: rank
  id: RatRankMVDGruntMiddle
  name: Милиционер МВД
  prefix: Милиционер
  paygrade: MVD2

- type: rank
  id: RatRankMVDGruntJunior
  name: Младший милиционер МВД
  prefix: Мл. милиционер
  paygrade: MVD1