- type: rank
  id: RatRankNCWLCommandSenior
  name: Генерал-полковник
  prefix: Генерал-полк.
  paygrade: O10

- type: rank
  id: RatRankNCWLCommandMiddle
  name: Генерал-лейтенант
  prefix: Генерал-лейт.
  paygrade: O9

- type: rank
  id: RatRankNCWLCommandJunior
  name: Генерал-майор
  prefix: Генерал-майор
  paygrade: O8

