using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.Administration.UI.Tabs.EconomyTab;

[GenerateTypedNameReferences]
public sealed partial class EconomyTabEntry : PanelContainer
{
    public EconomyTabEntry(
        string name,
        string id,
        double price,
        string priceKind,
        StyleBox styleBox,
        bool selected)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = name;
        IdLabel.Text = id;
        PriceLabel.Text = price.ToString("0.##");
        KindLabel.Text = priceKind;
        BackgroundColorPanel.PanelOverride = styleBox;

        if (selected)
        {
            var selectedStyle = new StyleBoxFlat(styleBox is StyleBoxFlat flat ? flat.BackgroundColor : Color.DarkSlateGray)
            {
                BorderColor = Color.FromHex("#5B8FD4"),
                BorderThickness = new Thickness(1),
            };
            BackgroundColorPanel.PanelOverride = selectedStyle;
        }
    }
}
