using System.Linq;
using Content.Client._Rat.Economy;
using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.Economy;
using Content.Shared.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Rat.Administration.UI.Tabs.EconomyTab;

[GenerateTypedNameReferences]
public sealed partial class EconomyTab : Control
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private readonly Color _altColor = Color.FromHex("#292B38");
    private readonly Color _defaultColor = Color.FromHex("#2F2F3B");

    private readonly EconomyPriceSystem _economy;
    private EconomyListCategory _category = EconomyListCategory.Items;
    private EconomyPriceEntry? _selected;
    private readonly List<EconomyPriceEntry> _entries = new();

    public EconomyTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _economy = IoCManager.Resolve<IEntityManager>().System<EconomyPriceSystem>();
        _economy.ListReceived += OnListReceived;
        _economy.PricesUpdated += OnPricesUpdated;

        CategoryOptions.AddItem(_loc.GetString("admin-menu-economy-category-items"), (int) EconomyListCategory.Items);
        CategoryOptions.AddItem(_loc.GetString("admin-menu-economy-category-vessels"), (int) EconomyListCategory.Vessels);
        CategoryOptions.OnItemSelected += ev =>
        {
            CategoryOptions.SelectId(ev.Id);
            _category = (EconomyListCategory) ev.Id;
            _selected = null;
            ClearStatus();
            UpdateSelectionUi();
            RequestList();
        };
        CategoryOptions.SelectId((int) _category);

        SearchLineEdit.OnTextEntered += _ => RequestList();
        RefreshListButton.OnPressed += _ => RequestList();
        SavePriceButton.OnPressed += OnSavePressed;

        SearchList.GenerateItem += GenerateButton;
        SearchList.ItemPressed += OnItemPressed;

        RequestList();
    }

    public void RefreshList()
    {
        RequestList();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            _economy.ListReceived -= OnListReceived;
            _economy.PricesUpdated -= OnPricesUpdated;
        }
    }

    private void OnPricesUpdated()
    {
        if (_entries.Count == 0)
            return;

        var protoManager = IoCManager.Resolve<IPrototypeManager>();

        foreach (var entry in _entries)
        {
            entry.CurrentPrice = entry.Category switch
            {
                EconomyListCategory.Items => _economy.GetEffectiveItemPrice(entry.Id, entry.BasePrice),
                EconomyListCategory.Vessels when protoManager.TryIndex<VesselPrototype>(entry.Id, out var vessel)
                    => _economy.GetVesselPrice(vessel),
                _ => entry.CurrentPrice,
            };
        }

        if (_selected != null)
        {
            var updated = _entries.FirstOrDefault(entry => entry.Id == _selected.Id);
            if (updated != null)
            {
                _selected = updated;
                PriceLineEdit.Text = _selected.CurrentPrice.ToString("0.##");
            }
        }

        PopulateList();
    }

    private void RequestList()
    {
        StatusLabel.Text = _loc.GetString("admin-menu-economy-loading");
        _economy.RequestList(_category, SearchLineEdit.Text);
    }

    private void OnListReceived(EconomyAdminListEvent msg)
    {
        if (msg.Category != _category)
            return;

        _entries.Clear();
        _entries.AddRange(msg.Entries);

        if (_selected != null)
        {
            _selected = _entries.FirstOrDefault(entry => entry.Id == _selected.Id);
            if (_selected != null)
                PriceLineEdit.Text = _selected.CurrentPrice.ToString("0.##");
        }

        PopulateList();
        StatusLabel.Text = _loc.GetString("admin-menu-economy-loaded", ("count", _entries.Count));
    }

    private void PopulateList()
    {
        var listData = new List<EconomyListData>();
        for (var i = 0; i < _entries.Count; i++)
        {
            var entry = _entries[i];
            listData.Add(new EconomyListData(entry, i % 2 == 0 ? _altColor : _defaultColor));
        }

        SearchList.PopulateList(listData);
        UpdateSelectionUi();
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not EconomyListData { Entry: var entry, BackgroundColor: var backgroundColor })
            return;

        var priceKind = entry.PriceKind?.ToString() ?? "-";
        var row = new EconomyTabEntry(
            entry.Name,
            entry.Id,
            entry.CurrentPrice,
            priceKind,
            new StyleBoxFlat { BackgroundColor = backgroundColor },
            _selected?.Id == entry.Id);

        button.AddChild(row);
        button.ToolTip = $"{entry.Name}\n{entry.Id}";
    }

    private void OnItemPressed(ButtonEventArgs args, ListData data)
    {
        if (data is not EconomyListData { Entry: var entry })
            return;

        _selected = entry;
        PriceLineEdit.Text = entry.CurrentPrice.ToString("0.##");
        UpdateSelectionUi();
        PopulateList();
    }

    private void OnSavePressed(ButtonEventArgs args)
    {
        if (_selected == null)
            return;

        if (!double.TryParse(PriceLineEdit.Text, out var price))
        {
            StatusLabel.Text = _loc.GetString("admin-menu-economy-invalid-price");
            return;
        }

        _economy.SetPrice(_category, _selected.Id, price);
        StatusLabel.Text = _loc.GetString("admin-menu-economy-saved", ("name", _selected.Name));
        _selected.CurrentPrice = price;
        PopulateList();
    }

    private void UpdateSelectionUi()
    {
        if (_selected == null)
        {
            SelectedEntryLabel.Text = _loc.GetString("admin-menu-economy-no-selection");
            SavePriceButton.Disabled = true;
            return;
        }

        SelectedEntryLabel.Text = _loc.GetString(
            "admin-menu-economy-selected",
            ("name", _selected.Name),
            ("id", _selected.Id));
        SavePriceButton.Disabled = false;
    }

    private void ClearStatus()
    {
        StatusLabel.Text = string.Empty;
    }
}

public record EconomyListData(EconomyPriceEntry Entry, Color BackgroundColor) : ListData;
