# Knights
- type: rank
  id: RatRankKnightLead
  name: Knight Grandmaster
  prefix: High Knight
  paygrade: K4

- type: rank
  id: RatRankKnightSenior
  name: Knight Master
  prefix: Master Knight
  paygrade: K3

- type: rank
  id: RatRankKnightMiddle
  name: Knight Banneret
  prefix: Sire
  paygrade: K2

- type: rank
  id: RatRankKnightJunior
  name: Knight
  prefix: Sir
  paygrade: K1

# Templar
- type: rank
  id: RatRankTemplarSenior
  name: Ordinator
  prefix: Ordinator
  paygrade: T3

- type: rank
  id: RatRankTemplarMiddle
  name: Praetor
  prefix: Praetor
  paygrade: T2

- type: rank
  id: RatRankTemplarJunior
  name: Executor
  prefix: Executor
  paygrade: T1