# Knights
- type: rank
  id: RatRankKnightLead
  name: Рыцарь-грандмастер
  prefix: Сир
  paygrade: K4

- type: rank
  id: RatRankKnightSenior
  name: Рыцарь-мастер
  prefix: Сир
  paygrade: K3

- type: rank
  id: RatRankKnightMiddle
  name: Рыцарь-баннерет
  prefix: Сир
  paygrade: K2

- type: rank
  id: RatRankKnightJunior
  name: Рыцарь
  prefix: Сир
  paygrade: K1
  
# Templar
- type: rank
  id: RatRankTemplarSenior
  name: Ординатор
  prefix: Ординатор
  paygrade: T3

- type: rank
  id: RatRankTemplarMiddle
  name: Претор
  prefix: Претор
  paygrade: T2

- type: rank
  id: RatRankTemplarJunior
  name: Экзекутор
  prefix: Экзекутор
  paygrade: T1