- type: rank
  id: RatRankNobleEmperor
  name: Император
  prefix: Император
  paygrade: EMP

- type: rank
  id: RatRankNobleHighStellarch
  name: Высший стелларх
  prefix: Высший стелларх
  paygrade: N9

- type: rank
  id: RatRankNobleStellarch
  name: Стелларх
  prefix: Стелларх
  paygrade: N8

- type: rank
  id: RatRankNobleArchduke
  name: Эрцгерцог
  prefix: Лорд-адмирал
  paygrade: N7

- type: rank
  id: RatRankNobleGrandDuke
  name: Великий герцог
  prefix: Лорд-адмирал
  paygrade: N6

- type: rank
  id: RatRankNobleDuke
  name: Герцог
  prefix: Герцог
  paygrade: N6

- type: rank
  id: RatRankNobleMarkgraf
  name: Маркграф
  prefix: Маркграф
  paygrade: N5

- type: rank
  id: RatRankNobleMarquis
  name: Маркиз
  prefix: Маркиз
  paygrade: N5

- type: rank
  id: RatRankNobleCount
  name: Граф
  prefix: Граф
  paygrade: N4

- type: rank
  id: RatRankNobleViscount
  name: Виконт
  prefix: Виконт
  paygrade: N3

- type: rank
  id: RatRankNobleBaron
  name: Барон
  prefix: Барон
  paygrade: N2

- type: rank
  id: RatRankNoblePatrician
  name: Патриций
  prefix: Патриций
  paygrade: N1