- type: rank
  id: RatRankFreeholderSenior
  name: Прониар
  prefix: Прониар
  paygrade: IC3

- type: rank
  id: RatRankFreeholderMiddle
  name: Йомен
  prefix: Йомен
  paygrade: IC2

- type: rank
  id: RatRankFreeholderJunior
  name: Фригольдер
  prefix: Фригольдер
  paygrade: IC1