- type: rank
  id: RatRankLevymanHead
  name: Центурион
  prefix: Центурион
  paygrade: L5

- type: rank
  id: RatRankLevymanLead
  name: Трибун
  prefix: Трибун
  paygrade: L4

- type: rank
  id: RatRankLevymanSenior
  name: Опцион
  prefix: Опцион
  paygrade: L3

- type: rank
  id: RatRankLevymanMiddle
  name: Проктор
  prefix: Проктор
  paygrade: L2

- type: rank
  id: RatRankLevymanJunior
  name: Леви
  prefix: Леви
  paygrade: L1