using System;
using System.IO;
using System.Threading.Tasks;
using Content.Shared._Rat.Audio.CustomBoombox;
using Robust.Client.Audio;
using Robust.Shared.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Rat.Audio.CustomBoombox;

[GenerateTypedNameReferences]
public sealed partial class CustomBoomboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IFileDialogManager _fileDialog = default!;
    private AudioSystem _audioSystem;

    private bool _playState;
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<float>? SetTime;
    public event Action<byte[], string>? OnUploadRequested;
    public event Action<float>? SetVolume;
    public event Action? OnClearPressed;

    private EntityUid? _audio;
    private float _lockTimer;

    public CustomBoomboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        UploadButton.OnPressed += args =>
        {
            _ = OnUploadPressedAsync();
        };

        PlayButton.OnPressed += _ =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += _ =>
        {
            OnStopPressed?.Invoke();
        };

        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;
        VolumeSlider.OnReleased += _ => { SetVolume?.Invoke(VolumeSlider.Value); _lockTimer = 0.5f; };
        ClearButton.OnPressed += _ => OnClearPressed?.Invoke();

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    private async Task OnUploadPressedAsync()
    {
        await using var stream = await _fileDialog.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("ogg")), FileAccess.Read);
        if (stream == null)
            return;

        var fileName = string.IsNullOrWhiteSpace(TrackNameInput.Text) ? "uploaded.ogg" : $"{TrackNameInput.Text}.ogg";
        var data = stream.CopyToArray();
        OnUploadRequested?.Invoke(data, fileName);
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        PlayButton.Text = playing
            ? Loc.GetString("jukebox-menu-buttonpause")
            : Loc.GetString("jukebox-menu-buttonplay");
    }

    public void SetVolumeValue(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(Math.Clamp(volume, 0f, 100f));
        VolumeNumberLabel.Text = $"{volume:0.##} %";
    }

    public void SetSelectedSong(string name, float length)
    {
        if (!string.IsNullOrEmpty(name))
            SongName.Text = name;
        else
            SongName.Text = "---";

        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f;

        VolumeSlider.Disabled = _lockTimer > 0f;
        VolumeNumberLabel.Text = $"{VolumeSlider.Value:0.##} %";

        AudioComponent? audio = null;
        if (_audio != null && _entManager.EntityExists(_audio.Value) && _entManager.TryGetComponent<AudioComponent>(_audio.Value, out var ac))
            audio = ac;

        if (audio != null)
        {
            DurationLabel.Text =
                $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(new ResolvedPathSpecifier(audio.FileName)):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = "00:00 / 00:00";
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || (_audio != null && _entManager.TryGetComponent<AudioComponent>(_audio.Value, out audio)))
            PlaybackSlider.SetValueWithoutEvent(audio!.PlaybackPosition);
        else
            PlaybackSlider.SetValueWithoutEvent(0f);

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }
}
