# Patriarch
- type: rank
  id: RatRankTFSCPatriarchSenior
  name: Секториальный патриарх
  prefix: Сект. Пат.
  paygrade: CD-P3

- type: rank
  id: RatRankTFSCPatriarchMiddle
  name: Патриарх
  prefix: Патриарх
  paygrade: CD-P2

- type: rank
  id: RatRankTFSCPatriarchJunior
  name: Младший патриарх
  prefix: Мл. Пат.
  paygrade: CD-P1

# Operative
- type: rank
  id: RatRankTFSCOperativeLead
  name: Ведущий оперативник
  prefix: Вед. опер.
  paygrade: CD-O4

- type: rank
  id: RatRankTFSCOperativeSenior
  name: Старший оператор
  prefix: Ст. опер.
  paygrade: CD-O3

- type: rank
  id: RatRankTFSCOperativeMiddle
  name: Оператор
  prefix: Опер.
  paygrade: CD-O2

- type: rank
  id: RatRankTFSCOperativeJunior
  name: Младший оператор
  prefix: Мл. опер.
  paygrade: CD-O1

# Researcher

- type: rank
  id: RatRankTFSCResearcherSenior
  name: Старший исследователь
  prefix: Ст. иссл.
  paygrade: CD-R3

- type: rank
  id: RatRankTFSCResearcherMiddle
  name: Исследователь
  prefix: Иссл.
  paygrade: CD-R2

- type: rank
  id: RatRankTFSCResearcherJunior
  name: Младший исследователь
  prefix: Мл. иссл.
  paygrade: CD-R1