# Coordinator
- type: rank
  id: RatRankTFSCCoordinatorHigh
  name: Директор
  prefix: Директор
  paygrade: ID-C5

- type: rank
  id: RatRankTFSCCoordinatorLead
  name: Заместитель директора
  prefix: Зам. дир.
  paygrade: ID-C4

- type: rank
  id: RatRankTFSCCoordinatorSenior
  name: Старший супервайзер
  prefix: Ст. суп.
  paygrade: ID-C3

- type: rank
  id: RatRankTFSCCoordinatorMiddle
  name: Супервайзер
  prefix: Суперв.
  paygrade: ID-C2

- type: rank
  id: RatRankTFSCCoordinatorJunior
  name: Младший супервайзер
  prefix: Мл. суп.
  paygrade: ID-C1

# Traumasec
- type: rank
  id: RatRankTFSCTraumasecHead
  name: Главный исполнитель
  prefix: Гл. исп.
  paygrade: ID-E5

- type: rank
  id: RatRankTFSCTraumasecLead
  name: Исполнитель-специалист
  prefix: Спец.
  paygrade: ID-E4

- type: rank
  id: RatRankTFSCTraumasecSenior
  name: Исполнитель 1го класса
  prefix: Исп. 1го кл.
  paygrade: ID-E3

- type: rank
  id: RatRankTFSCTraumasecMiddle
  name: Исполнитель 2го класса
  prefix: Исп. 2го кл.
  paygrade: ID-E2

- type: rank
  id: RatRankTFSCTraumasecJunior
  name: Исполнитель 3го класса
  prefix: Исп. 3го кл.
  paygrade: ID-E1

# Ripperdoc
- type: rank
  id: RatRankTFSCRipperdocLead
  name: Ведущий хирург
  prefix: Вед. хир.
  paygrade: ID-D4

- type: rank
  id: RatRankTFSCRipperdocSenior
  name: Старший хирург
  prefix: Ст. хир.
  paygrade: ID-D3

- type: rank
  id: RatRankTFSCRipperdocMiddle
  name: Хирург
  prefix: Хирург
  paygrade: ID-D2

- type: rank
  id: RatRankTFSCRipperdocJunior
  name: Интерн
  prefix: Интерн
  paygrade: ID-D1