using Content.Client._Rat.Economy;
using Content.Shared.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class VesselRow : PanelContainer
{
    public event Action<string?>? OnPurchasePressed;

    public VesselRow(VesselPrototype vessel, bool access, int displayPrice)
    {
        RobustXamlLoader.Load(this);

        VesselName.Text = vessel.Name;
        CustomNameEdit.PlaceHolder = Loc.GetString("shipyard-custom-name-placeholder");

        var tooltip = new Tooltip();
        tooltip.SetMessage(FormattedMessage.FromMarkup(vessel.Description));
        Purchase.TooltipSupplier = _ => tooltip;
        Purchase.Disabled = !access;
        Purchase.OnPressed += _ => OnPurchasePressed?.Invoke(CustomNameEdit.Text.Length > 0 ? CustomNameEdit.Text : null);

        Price.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", displayPrice));
    }

    public VesselRow(VesselPrototype vessel, bool access) : this(vessel, access, IoCManager.Resolve<IEntityManager>().System<EconomyPriceSystem>().GetVesselPrice(vessel))
    {
    }
}
