using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.LifeInsurance;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.LifeInsurance;

[GenerateTypedNameReferences]
public sealed partial class LifeInsuranceWindow : FancyWindow
{
    /// <summary>Raw material units are shown in UI divided by this (matches exotic protein stack convention).</summary>
    private const int ProteinDisplayDivisor = 500;

    private readonly List<LifeInsuranceTargetEntry> _targets = new();
    private readonly List<LifeInsuranceSpawnMachineEntry> _spawnMachines = new();
    private readonly List<int> _filteredIndices = new();
    private int? _selectedFilteredIndex;
    private int _requiredProteins;
    private bool _suppressSpawnMachineNotify;

    /// <summary>Target mob, and spawn machine chosen in the dropdown (invalid if none).</summary>
    public event Action<NetEntity, NetEntity>? InsurePressed;
    public event Action<NetEntity>? VoidPressed;
    public event Action? EjectPressed;
    public event Action<NetEntity, NetEntity>? SpawnMachineSelected;

    public LifeInsuranceWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("life-insurance-console-title");
        PlayersList.OnItemSelected += OnPlayerSelected;
        SearchLine.OnTextChanged += _ => RebuildList();
        InsureButton.OnPressed += _ => OnInsureButtonPressed();
        VoidButton.OnPressed += _ => OnVoidButtonPressed();
        EjectButton.OnPressed += _ => EjectPressed?.Invoke();
        SpawnMachineOption.OnItemSelected += OnSpawnMachineItemSelected;
        SetDetails(null);
    }

    public void UpdateState(LifeInsuranceConsoleState state)
    {
        _targets.Clear();
        _targets.AddRange(state.Targets);
        _spawnMachines.Clear();
        _spawnMachines.AddRange(state.SpawnMachines);
        _requiredProteins = state.RequiredProteins;

        ProteinsLabel.Text = Loc.GetString("life-insurance-stored-proteins",
            ("stored", state.StoredProteins / ProteinDisplayDivisor));

        RebuildSpawnMachinePicker();
        RebuildList();
    }

    private void OnPlayerSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemIndex < 0 || args.ItemIndex >= _filteredIndices.Count)
            return;

        _selectedFilteredIndex = args.ItemIndex;
        SetDetails(GetSelectedEntry());
    }

    private void OnInsureButtonPressed()
    {
        var target = GetSelectedEntry();
        if (target == null || target.AlreadyInsured || target.HasPendingRespawn)
            return;

        var spawn = default(NetEntity);
        if (_spawnMachines.Count > 0
            && SpawnMachineOption.SelectedId >= 0
            && SpawnMachineOption.SelectedId < _spawnMachines.Count)
        {
            spawn = _spawnMachines[SpawnMachineOption.SelectedId].Entity;
        }

        InsurePressed?.Invoke(target.Target, spawn);
    }

    private void OnVoidButtonPressed()
    {
        var target = GetSelectedEntry();
        if (target == null || (!target.AlreadyInsured && !target.HasPendingRespawn))
            return;

        VoidPressed?.Invoke(target.Target);
    }

    private LifeInsuranceTargetEntry? GetSelectedEntry()
    {
        if (_selectedFilteredIndex == null
            || _selectedFilteredIndex.Value < 0
            || _selectedFilteredIndex.Value >= _filteredIndices.Count)
            return null;

        return _targets[_filteredIndices[_selectedFilteredIndex.Value]];
    }

    private void RebuildList()
    {
        _filteredIndices.Clear();
        PlayersList.Clear();

        var filter = SearchLine.Text.Trim();
        for (var i = 0; i < _targets.Count; i++)
        {
            var entry = _targets[i];
            if (!string.IsNullOrWhiteSpace(filter)
                && !entry.Name.Contains(filter, StringComparison.OrdinalIgnoreCase)
                && !entry.RoleName.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            _filteredIndices.Add(i);
            string status;
            if (entry.AlreadyInsured)
                status = Loc.GetString("life-insurance-list-status-insured");
            else if (entry.HasPendingRespawn)
                status = Loc.GetString("life-insurance-list-status-pending");
            else
                status = Loc.GetString("life-insurance-list-status-not-insured");
            PlayersList.AddItem($"{entry.Name} — {entry.RoleName} ({status})");
        }

        if (_filteredIndices.Count == 0)
        {
            _selectedFilteredIndex = null;
            SetDetails(null);
            return;
        }

        if (_selectedFilteredIndex == null || _selectedFilteredIndex.Value >= _filteredIndices.Count)
            _selectedFilteredIndex = 0;

        SetDetails(GetSelectedEntry());
    }

    private void SetDetails(LifeInsuranceTargetEntry? entry)
    {
        if (entry == null)
        {
            DetailsName.Text = Loc.GetString("life-insurance-no-selection");
            DetailsRole.Text = string.Empty;
            DetailsStatus.Text = string.Empty;
            DetailsStatus.FontColorOverride = null;
            ClearQuoteBox();
            InsureButton.Disabled = true;
            VoidButton.Disabled = true;
            SpawnMachineTitle.Visible = false;
            SpawnMachineOption.Visible = false;
            return;
        }

        DetailsName.Text = Loc.GetString("life-insurance-details-name", ("name", entry.Name));
        DetailsRole.Text = Loc.GetString("life-insurance-details-role", ("role", entry.RoleName));

        string statusText;
        Color statusColor;
        if (entry.AlreadyInsured)
        {
            statusText = Loc.GetString("life-insurance-details-status-insured");
            statusColor = Color.FromHex("#4CAF50");
        }
        else if (entry.HasPendingRespawn)
        {
            statusText = Loc.GetString("life-insurance-details-status-pending");
            statusColor = Color.FromHex("#FFA726");
        }
        else
        {
            statusText = Loc.GetString("life-insurance-details-status-not-insured");
            statusColor = Color.FromHex("#9E9E9E");
        }

        DetailsStatus.Text = statusText;
        DetailsStatus.FontColorOverride = statusColor;

        var showSpawnPicker = _spawnMachines.Count > 0;
        SpawnMachineTitle.Visible = showSpawnPicker;
        SpawnMachineOption.Visible = showSpawnPicker;
        if (showSpawnPicker)
            SyncSpawnMachineOptionFromEntry(entry);

        if (!entry.AlreadyInsured && !entry.HasPendingRespawn)
        {
            DetailsQuoteText.Visible = true;
            DetailsQuoteText.Text = Loc.GetString("life-insurance-details-quote",
                ("proteins", _requiredProteins / ProteinDisplayDivisor),
                ("credits", entry.NextCreditsPrice));
        }
        else
        {
            ClearQuoteBox();
        }

        InsureButton.Disabled = entry.AlreadyInsured || entry.HasPendingRespawn || !_spawnMachines.Any();
        VoidButton.Disabled = !(entry.AlreadyInsured || entry.HasPendingRespawn);
    }

    private void RebuildSpawnMachinePicker()
    {
        _suppressSpawnMachineNotify = true;
        SpawnMachineOption.Clear();
        if (_spawnMachines.Count == 0)
        {
            SpawnMachineOption.AddItem(Loc.GetString("life-insurance-no-spawn-machines"), 0);
            SpawnMachineOption.Disabled = true;
        }
        else
        {
            SpawnMachineOption.Disabled = false;
            for (var i = 0; i < _spawnMachines.Count; i++)
                SpawnMachineOption.AddItem(_spawnMachines[i].Name, i);
        }

        _suppressSpawnMachineNotify = false;
    }

    private void SyncSpawnMachineOptionFromEntry(LifeInsuranceTargetEntry entry)
    {
        if (_spawnMachines.Count == 0)
            return;

        _suppressSpawnMachineNotify = true;
        if (entry.BoundSpawnMachine is { } bound)
        {
            var idx = _spawnMachines.FindIndex(e => e.Entity == bound);
            SpawnMachineOption.SelectId(idx >= 0 ? idx : 0);
        }
        else
        {
            SpawnMachineOption.SelectId(0);
        }

        _suppressSpawnMachineNotify = false;
    }

    private void OnSpawnMachineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_suppressSpawnMachineNotify)
            return;

        var entry = GetSelectedEntry();
        if (entry == null || args.Id < 0 || args.Id >= _spawnMachines.Count)
            return;

        SpawnMachineSelected?.Invoke(entry.Target, _spawnMachines[args.Id].Entity);
    }

    private void ClearQuoteBox()
    {
        DetailsQuoteText.Visible = false;
        DetailsQuoteText.Text = string.Empty;
    }
}
