using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.Overwatch;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Rat.Overwatch;

/// <summary>
/// Overwatch console window for monitoring and spectating faction members.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OverwatchWindow : FancyWindow
{
    private const int MinMembersGridWidth = 400;
    private const int MinAdminPanelWidth = 350;
    private const int WindowWidth = 1200;
    private const int WindowHeight = 750;
    private const int HeaderMarginTop = 5;
    private const int HeaderMarginBottom = 2;
    private const int SquadFilterAllId = 0;
    private const int SquadFilterUnassignedId = -1;
    private const int AnnouncementTargetAllId = 0;

    private OverwatchBoundUserInterface? _ui;
    private readonly Dictionary<NetEntity, OverwatchMemberRow> _memberRows = new();
    private List<OverwatchMemberData> _allMembers = new();

    // Preserves per-member watch state so UI refreshes don't reset the camera view.
    private readonly Dictionary<NetEntity, bool> _watchingStateCache = new();

    private bool _anyDropdownOpen;
    private bool _justOpenedSquadSelect;
    private OverwatchUpdateState? _pendingState;

    private OverwatchMemberStatus? _statusFilter;
    private int? _squadFilterId;
    private string _searchQuery = "";

    private Dictionary<int, string> _availableSquads = new();
    private Color _factionColor;

    public OverwatchWindow()
    {
        RobustXamlLoader.Load(this);

        StopWatchingButton.OnPressed += _ =>
        {
            _ui?.StopWatching();

            foreach (var row in _memberRows.Values)
            {
                row.SetWatching(false);
            }

            _watchingStateCache.Clear();
            StopWatchingButton.Visible = false;
        };

        OnKeyBindDown += evt =>
        {
            if (_justOpenedSquadSelect)
            {
                _justOpenedSquadSelect = false;
                return;
            }
            CloseAllSquadSelects();
        };

        InitializeFilters();
        InitializeAdminPanel();
    }

    private void InitializeFilters()
    {
        StatusFilter.AddItem(Loc.GetString("overwatch-status-all"), SquadFilterAllId);
        StatusFilter.AddItem(Loc.GetString("overwatch-status-alive"), (int)OverwatchMemberStatus.Alive + 1);
        StatusFilter.AddItem(Loc.GetString("overwatch-status-ssd"), (int)OverwatchMemberStatus.SSD + 1);
        StatusFilter.AddItem(Loc.GetString("overwatch-status-dead"), (int)OverwatchMemberStatus.Dead + 1);

        StatusFilter.OnItemSelected += args =>
        {
            _statusFilter = args.Id == SquadFilterAllId
            ? null
            : (OverwatchMemberStatus)(args.Id - 1);
            StatusFilter.SelectId(args.Id);
            ApplyFilters();
        };
        StatusFilter.SelectId(SquadFilterAllId);

        _squadFilterId = SquadFilterAllId;

        SquadFilter.AddItem(Loc.GetString("overwatch-squad-all"), SquadFilterAllId);
        SquadFilter.AddItem(Loc.GetString("overwatch-squad-unassigned"), SquadFilterUnassignedId);
        SquadFilter.SelectId(SquadFilterAllId);

        SquadFilter.OnItemSelected += args =>
        {
            _squadFilterId = args.Id;
            SquadFilter.SelectId(args.Id);
            ApplyFilters();
        };

        SearchInput.OnTextEntered += _ =>
        {
            _searchQuery = SearchInput.Text.Trim();
            ApplyFilters();
        };
        SearchInput.OnTextChanged += _ =>
        {
            _searchQuery = SearchInput.Text.Trim();
            ApplyFilters();
        };
    }

    public void Initialize(OverwatchBoundUserInterface ui)
    {
        _ui = ui;
    }

    private void OnMemberStartWatching(OverwatchMemberRow selectedRow)
    {
        foreach (var row in _memberRows.Values)
        {
            if (row != selectedRow)
            {
                row.SetWatching(false);
                _watchingStateCache[row.Member] = false;
            }
        }

        StopWatchingButton.Visible = true;
    }

    public void UpdateState(OverwatchUpdateState state)
    {
        if (_ui == null)
            return;

        _allMembers = state.Members;
        _factionColor = state.FactionColor;

        if (!string.IsNullOrEmpty(state.SearchQuery) && string.IsNullOrEmpty(_searchQuery))
        {
            _searchQuery = state.SearchQuery;
            SearchInput.Text = state.SearchQuery;
        }

        var squadsChanged = _availableSquads.Count != state.AvailableSquads.Count ||
                            state.AvailableSquads.Any(kvp =>
                                !_availableSquads.ContainsKey(kvp.Key) ||
                                _availableSquads[kvp.Key] != kvp.Value);
        _availableSquads = state.AvailableSquads;

        if (_anyDropdownOpen)
        {
            _pendingState = state;
            return;
        }

        _pendingState = null;
        ApplyStateToUi(squadsChanged);
    }

    private void ApplyStateToUi(bool squadsChanged)
    {
        AdminPanel.Visible = true;

        if (squadsChanged)
            UpdateSquadFilter(_availableSquads);

        UpdateSquadsList(_availableSquads);
        ApplyFilters();
        StopWatchingButton.Visible = GetCurrentWatchedEntity() != null;
    }

    public void CloseAllSquadSelects()
    {
        var anyWasOpen = false;
        foreach (var row in _memberRows.Values)
        {
            if (row.SquadSelect.Visible)
            {
                row.SquadSelect.Visible = false;
                row.SquadButton.Visible = true;
                anyWasOpen = true;
            }
        }
        if (anyWasOpen)
        {
            _anyDropdownOpen = false;

            if (_pendingState != null)
            {
                var pending = _pendingState;
                _pendingState = null;
                UpdateState(pending);
            }
        }
    }

    public void SetJustOpenedSquadSelect()
    {
        _justOpenedSquadSelect = true;
    }

    private void UpdateSquadFilter(Dictionary<int, string> availableSquads)
    {
        var currentSelection = SquadFilter.SelectedId;
        var currentAnnouncementSelection = AnnouncementTarget.SelectedId;

        SquadFilter.Clear();
        SquadFilter.AddItem(Loc.GetString("overwatch-squad-all"), SquadFilterAllId);
        SquadFilter.AddItem(Loc.GetString("overwatch-squad-unassigned"), SquadFilterUnassignedId);

        foreach (var squad in availableSquads.OrderBy(s => s.Value))
        {
            SquadFilter.AddItem(squad.Value, squad.Key);
        }

        _availableSquads = availableSquads;
        SquadFilter.SelectId(currentSelection);
        UpdateAnnouncementTargets(currentAnnouncementSelection);
    }

    private void UpdateAnnouncementTargets(int? currentSelection = null)
    {
        AnnouncementTarget.Clear();
        AnnouncementTarget.AddItem(Loc.GetString("overwatch-admin-announcement-to-all"), AnnouncementTargetAllId);

        foreach (var squad in _availableSquads.OrderBy(s => s.Value))
        {
            AnnouncementTarget.AddItem(squad.Value, squad.Key);
        }

        var selection = currentSelection is { } id &&
                    (id == AnnouncementTargetAllId || _availableSquads.ContainsKey(id))
        ? id
        : AnnouncementTargetAllId;

    AnnouncementTarget.SelectId(selection);
    }

    private void UpdateSquadsList(Dictionary<int, string> squads)
    {
        SquadsList.DisposeAllChildren();

        foreach (var squad in squads.OrderBy(s => s.Value))
        {
            var memberCount = _allMembers.Count(m => m.SquadId == squad.Key);

            var squadBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 5,
                HorizontalExpand = true
            };

            var squadLabel = new Label
            {
                Text = $"{squad.Value} {Loc.GetString("overwatch-squad-member-count", ("count", memberCount))}",
                HorizontalExpand = true
            };

            var deleteButton = new Button
            {
                Text = Loc.GetString("overwatch-squad-delete-button"),
                Disabled = memberCount > 0
            };

            if (memberCount == 0)
            {
                deleteButton.OnPressed += _ => _ui?.DeleteSquad(squad.Key);
            }

            squadBox.AddChild(squadLabel);
            squadBox.AddChild(deleteButton);
            SquadsList.AddChild(squadBox);
        }
    }

    private void InitializeAdminPanel()
    {
        AnnouncementTarget.AddItem(Loc.GetString("overwatch-admin-announcement-to-all"), AnnouncementTargetAllId);

        AnnouncementTarget.OnItemSelected += args =>
        {
            AnnouncementTarget.SelectId(args.Id);
        };
        AnnouncementTarget.SelectId(AnnouncementTargetAllId);

        SendAnnouncementButton.OnPressed += _ =>
        {
            var message = AnnouncementInput.Text?.Trim();
            if (string.IsNullOrEmpty(message))
                return;

            var targetSquadId = AnnouncementTarget.SelectedId == AnnouncementTargetAllId
                ? null
                : GetSquadIdByIndex(AnnouncementTarget.SelectedId);

            _ui?.SendAnnouncement(message, targetSquadId);
            AnnouncementInput.Text = "";
        };

        CreateSquadButton.OnPressed += _ =>
        {
            var squadName = NewSquadNameInput.Text?.Trim();

            if (string.IsNullOrEmpty(squadName))
                return;

            _ui?.CreateSquad(squadName);
            NewSquadNameInput.Text = "";
        };
    }

    private int? GetSquadIdByIndex(int index)
    {
        if (index == AnnouncementTargetAllId)
            return null;

        return index;
    }

    private void ApplyFilters()
    {
        int? squadFilterId = null;
        bool filterUnassigned = false;

        if (_squadFilterId.HasValue)
        {
            if (_squadFilterId.Value == SquadFilterUnassignedId)
            {
                filterUnassigned = true;
            }
            else if (_squadFilterId.Value != SquadFilterAllId)
            {
                squadFilterId = _squadFilterId.Value;
            }
        }

        var filteredMembers = _allMembers.Where(m =>
        {
            if (_statusFilter.HasValue && m.Status != _statusFilter.Value)
                return false;

            if (filterUnassigned)
            {
                if (m.SquadId.HasValue)
                    return false;
            }
            else if (squadFilterId.HasValue)
            {
                if (!m.SquadId.HasValue || m.SquadId.Value != squadFilterId.Value)
                    return false;
            }

            if (!string.IsNullOrEmpty(_searchQuery) &&
                !m.Name.Contains(_searchQuery, StringComparison.OrdinalIgnoreCase))
                return false;

            return true;
        }).ToList();

        UpdateMembersGrid(filteredMembers);
    }

    private void UpdateMembersGrid(List<OverwatchMemberData> members)
    {
        MembersGrid.DisposeAllChildren();
        _memberRows.Clear();

        var currentWatched = GetCurrentWatchedEntity();

        _watchingStateCache.Clear();
        if (currentWatched.HasValue)
        {
            _watchingStateCache[currentWatched.Value] = true;
        }

        var membersBySquad = new Dictionary<int, List<OverwatchMemberData>>();

        foreach (var member in members)
        {
            var squadId = member.SquadId ?? SquadFilterUnassignedId;
            if (!membersBySquad.ContainsKey(squadId))
            {
                membersBySquad[squadId] = new List<OverwatchMemberData>();
            }
            membersBySquad[squadId].Add(member);
        }

        var sortedSquads = membersBySquad.OrderBy(kvp =>
        {
            if (kvp.Key == SquadFilterUnassignedId)
                return "";
            return _availableSquads.TryGetValue(kvp.Key, out var name) ? name : kvp.Key.ToString();
        }).ToList();

        foreach (var squad in sortedSquads)
        {
            string squadName;
            if (squad.Key == SquadFilterUnassignedId)
            {
                squadName = Loc.GetString("overwatch-squad-unassigned");
            }
            else if (_availableSquads.TryGetValue(squad.Key, out var name))
            {
                squadName = $"{name} {Loc.GetString("overwatch-squad-member-count", ("count", squad.Value.Count))}";
            }
            else
            {
                squadName = $"{Loc.GetString("overwatch-squad-label")} {squad.Key} {Loc.GetString("overwatch-squad-member-count", ("count", squad.Value.Count))}";
            }

            var headerLabel = new Label
            {
                Text = squadName,
                FontColorOverride = _factionColor,
                Margin = new Thickness(0, HeaderMarginTop, 0, HeaderMarginBottom)
            };
            MembersGrid.AddChild(headerLabel);

            foreach (var memberData in squad.Value)
            {
                if (_ui == null)
                    continue;

                var row = new OverwatchMemberRow(memberData, _ui, OnMemberStartWatching, () => _availableSquads, _availableSquads, (isOpen) => _anyDropdownOpen = isOpen, this);

                row.SetWatching(currentWatched == memberData.Member);

                MembersGrid.AddChild(row);
                _memberRows[memberData.Member] = row;
            }
        }
    }

    public void SetWatching(NetEntity member, bool isWatching)
    {
        _watchingStateCache[member] = isWatching;

        if (_memberRows.TryGetValue(member, out var row))
        {
            row.SetWatching(isWatching);
        }

        StopWatchingButton.Visible = _watchingStateCache.Values.Any(v => v);
    }

    private NetEntity? GetCurrentWatchedEntity()
    {
        var playerManager = IoCManager.Resolve<IPlayerManager>();
        var entManager = IoCManager.Resolve<IEntityManager>();
        if (playerManager.LocalEntity is { } localPlayer &&
            entManager.TryGetComponent<RatOverwatchWatchingComponent>(localPlayer, out var watchingComp) &&
            watchingComp.Watching.HasValue)
        {
            return entManager.GetNetEntity(watchingComp.Watching.Value);
        }
        return null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var currentWatched = GetCurrentWatchedEntity();
        var changed = false;

        if (currentWatched.HasValue)
        {
            if (!_watchingStateCache.TryGetValue(currentWatched.Value, out var isWatching) || !isWatching)
            {
                changed = true;
            }

            foreach (var (member, isWatch) in _watchingStateCache.ToList())
            {
                if (member != currentWatched.Value && isWatch)
                {
                    _watchingStateCache[member] = false;
                    changed = true;
                }
            }

            if (changed)
            {
                _watchingStateCache[currentWatched.Value] = true;
                foreach (var (member, row) in _memberRows)
                {
                    row.SetWatching(member == currentWatched.Value);
                }
                StopWatchingButton.Visible = true;
            }
        }
        else
        {
            foreach (var (member, isWatch) in _watchingStateCache.ToList())
            {
                if (isWatch)
                {
                    _watchingStateCache[member] = false;
                    changed = true;
                }
            }

            if (changed)
            {
                foreach (var row in _memberRows.Values)
                {
                    row.SetWatching(false);
                }
                StopWatchingButton.Visible = false;
            }
        }
    }

    /// <inheritdoc/>
    protected override void Dispose(bool disposing)
    {
        foreach (var row in _memberRows.Values)
        {
            row.Dispose();
        }
        _memberRows.Clear();
        base.Dispose(disposing);
    }
}

/// <summary>
/// A single member row inside the Overwatch window grid.
/// </summary>
public sealed class OverwatchMemberRow : BoxContainer
{
    private readonly Label _nameLabel;
    private readonly Label _jobLabel;
    private readonly Label _statusLabel;
    private readonly Label _coordinatesLabel;
    private readonly Button _viewButton;
    private readonly Button _squadButton;
    private readonly OptionButton _squadSelect;
    private readonly OverwatchBoundUserInterface _ui;
    private readonly Action<OverwatchMemberRow> _onStartWatching;
    private readonly Func<Dictionary<int, string>> _getSquadsFunc;
    private readonly Dictionary<int, string>? _availableSquadsCache;
    private readonly Action<bool>? _onDropdownOpenChanged;
    private readonly OverwatchWindow? _window;
    private NetEntity _member;
    private int? _currentSquadId;
    private System.Numerics.Vector2? _coordinates;

    public bool IsWatching { get; private set; }

    public NetEntity Member => _member;

    public OptionButton SquadSelect => _squadSelect;

    public Button SquadButton => _squadButton;

    public OverwatchMemberRow(
        OverwatchMemberData data,
        OverwatchBoundUserInterface ui,
        Action<OverwatchMemberRow> onStartWatching,
        Func<Dictionary<int, string>> getSquadsFunc,
        Dictionary<int, string>? availableSquadsCache = null,
        Action<bool>? onDropdownOpenChanged = null,
        OverwatchWindow? window = null)
    {
        _ui = ui;
        _member = data.Member;
        _onStartWatching = onStartWatching;
        _getSquadsFunc = getSquadsFunc;
        _currentSquadId = data.SquadId;
        _coordinates = data.Coordinates;
        _availableSquadsCache = availableSquadsCache;
        _onDropdownOpenChanged = onDropdownOpenChanged;
        _window = window;

        Orientation = LayoutOrientation.Horizontal;
        SeparationOverride = 5;
        HorizontalExpand = true;

        _nameLabel = new Label{};
        _jobLabel = new Label();
        _statusLabel = new Label();
        _coordinatesLabel = new Label();
        _viewButton = new Button { Text = Loc.GetString("overwatch-member-view-camera-button"), MinSize = new Vector2i(120, 0) };
        _squadButton = new Button { Text = Loc.GetString("overwatch-member-squad-assign"), MinSize = new Vector2i(60, 0) };
        _squadSelect = new OptionButton { MinSize = new Vector2i(150, 0), Visible = false };

        AddChild(_nameLabel);
        AddChild(_jobLabel);
        AddChild(new Label { Text = "|" });
        AddChild(_statusLabel);
        AddChild(_coordinatesLabel);
        AddChild(new Label { Text = "|" });
        AddChild(_viewButton);
        AddChild(_squadButton);
        AddChild(_squadSelect);

        _viewButton.OnPressed += _ =>
        {
            _onStartWatching(this);
            _ui.ViewCamera(_member);
            _window?.SetWatching(_member, true);
        };

        _squadButton.OnPressed += _ =>
        {
            RefreshSquadSelect();
            _squadSelect.Visible = true;
            _squadButton.Visible = false;
            _onDropdownOpenChanged?.Invoke(true);
            _window?.SetJustOpenedSquadSelect();
        };

        _squadSelect.OnItemSelected += args =>
        {
            _squadSelect.Visible = false;
            _squadButton.Visible = true;
            _onDropdownOpenChanged?.Invoke(false);
            if (args.Id == -1)
            {
                _ui?.RemoveSquadMember(_member);
                _currentSquadId = null;
            }
            else
            {
                _ui?.AssignSquad(_member, args.Id);
                _currentSquadId = args.Id;
            }

            _squadSelect.SelectId(args.Id);
        };

        Update(data);
    }

    public void RefreshSquadSelect()
    {
        var squads = _availableSquadsCache ?? _getSquadsFunc();

        _squadSelect.Clear();
        _squadSelect.AddItem(Loc.GetString("overwatch-member-squad-no-squad"), -1);

        foreach (var squad in squads.OrderBy(s => s.Value))
        {
            _squadSelect.AddItem(squad.Value, squad.Key);
        }

        if (_currentSquadId.HasValue && squads.ContainsKey(_currentSquadId.Value))
        {
            _squadSelect.SelectId(_currentSquadId.Value);
        }
        else
        {
            _squadSelect.SelectId(-1);
        }
    }

    public void Update(OverwatchMemberData data)
    {
        if (_squadSelect.Visible)
        {
            _squadSelect.Visible = false;
            _squadButton.Visible = true;
            _onDropdownOpenChanged?.Invoke(false);
        }

        _nameLabel.Text = data.Name;
        _jobLabel.Text = data.JobTitle;
        _statusLabel.Text = data.Status switch
        {
            OverwatchMemberStatus.Alive => Loc.GetString("overwatch-member-status-alive"),
            OverwatchMemberStatus.SSD => Loc.GetString("overwatch-member-status-ssd"),
            OverwatchMemberStatus.Dead => Loc.GetString("overwatch-member-status-dead"),
            _ => Loc.GetString("overwatch-member-status-unknown")
        };

        _statusLabel.FontColorOverride = data.Status switch
        {
            OverwatchMemberStatus.Alive => Color.Green,
            OverwatchMemberStatus.SSD => Color.Yellow,
            OverwatchMemberStatus.Dead => Color.Red,
            _ => Color.White
        };

        _coordinates = data.Coordinates;
        _coordinatesLabel.Text = data.Coordinates.HasValue
            ? Loc.GetString("overwatch-member-coordinates", ("x", Math.Round(data.Coordinates.Value.X, 1)), ("y", Math.Round(data.Coordinates.Value.Y, 1)))
            : Loc.GetString("overwatch-member-coordinates-none");

        _viewButton.Disabled = !data.HasCamera;
        _currentSquadId = data.SquadId;
        UpdateButtonState();
    }

    public void SetWatching(bool isWatching)
    {
        IsWatching = isWatching;
        UpdateButtonState();
    }

    private void UpdateButtonState()
    {
        if (IsWatching)
        {
            _viewButton.Text = Loc.GetString("overwatch-member-watching-button");
            _viewButton.StyleClasses.Clear();
            _viewButton.StyleClasses.Add("openBoth");
        }
        else if (_viewButton.Disabled)
        {
            _viewButton.Text = Loc.GetString("overwatch-member-no-camera-button");
            _viewButton.StyleClasses.Clear();
        }
        else
        {
            _viewButton.Text = Loc.GetString("overwatch-member-view-camera-button");
            _viewButton.StyleClasses.Clear();
        }
    }
}
